export type Article = {
  num: string
  title: string
  blurb: string
  titleJa: string
  blurbJa: string
  category: 'culture' | 'spirituality' | 'theory' | 'history' | 'science' | 'japan' | 'triskelion'
  categoryLabel: string
  categoryLabelJa: string
  slug: string
  image?: string
  authored?: 'human' | 'ai'
}

export const articles: Article[] = [
  // CULTURE & SOCIETY
  { num: '01', title: 'The Geography of Power: Floodplain vs Fractured-Sea Cultures', blurb: 'Why whole civilisations think differently — and why the answer lies in the shape of the land. The first article in the Geography of Power series.', titleJa: '権力の地理学：氾濫原文明と分裂海文明', blurbJa: '文明全体がなぜ異なる思考をするのか——その答えは土地の形にある。権力の地理学シリーズの第一回。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'floodplain-vs-fractured-sea', image: '/images/articles/floodplain-vs-fractured-sea.png' },
  { num: '01b', title: 'The Geography of Power: The Geography of Hierarchy', blurb: 'Fragmented geography produces competition. But the same competitive pressure also produces something else — hereditary hierarchy built around bloodlines, land, and family groups.', titleJa: '権力の地理学：階層の地理', blurbJa: '分断された地形は競争を生む。しかし同じ競争圧力は別のものも生み出す——血統、土地、家族集団を中心とした世襲的階層だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'geography-of-hierarchy', image: '/images/articles/geography-of-hierarchy.png' },
  { num: '01c', title: 'The Geography of Power: Two Shapes of Hierarchy', blurb: 'In Japan, hierarchy describes a relationship in a context. In Victorian England, it described a person. The difference — relational vs ontological — has consequences that still echo today.', titleJa: '権力の地理学：二つの階層の形', blurbJa: '日本では、階層は文脈の中の関係を表す。ビクトリア朝イギリスでは、人そのものを表した。関係的対存在論的——その違いは今日も響き続けている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'two-shapes-of-hierarchy', image: '/images/articles/two-shapes-of-hierarchy.png' },
  { num: '02', title: 'Why Dating Apps Structurally Fail Men — And How to Fix Them', blurb: 'The architecture of modern dating apps creates a structural mismatch that no better photo can fix.', titleJa: 'マッチングアプリが男性に不利な構造的理由', blurbJa: '現代のマッチングアプリの設計には、写真を改善しても解決できない構造的ミスマッチがある。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'dating-apps-fail-men', image: '/images/articles/dating-apps-fail-men.jpeg' },
  { num: '03', title: 'Debate Cultures vs Scolding Cultures', blurb: 'Two fundamentally different ways of handling disagreement — and what they reveal about a society.', titleJa: '議論文化と叱責文化', blurbJa: '意見の相違への二つの根本的アプローチ——それは社会の本質を映し出す。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'debate-vs-scolding-cultures', image: '/images/articles/debate-vs-scolding-cultures.png' },
  { num: '04', title: 'Nordic Social Scripts: What Scandinavia Gets Right About Social Pressure', blurb: 'The hidden rules governing Scandinavian social life — and why they might be the most sophisticated system in the world.', titleJa: '北欧の社会スクリプト：スカンジナビアが社会的圧力について正しいこと', blurbJa: '北欧の社会生活を支配する隠れたルール——それは世界で最も洗練されたシステムかもしれない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'nordic-social-scripts', image: '/images/articles/nordic-social-scripts.jpeg' },
  { num: '05', title: 'Was Edo Japan Happier Than Modern Japan?', blurb: 'A pre-industrial society with no growth economy, near-zero crime, and high life satisfaction. What can it teach us?', titleJa: '江戸時代の日本は現代より幸福だったのか', blurbJa: '経済成長なし、ほぼゼロの犯罪率、高い生活満足度——前工業化社会から何を学べるか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'edo-japan-happiness', image: '/images/articles/edo-japan-happiness.png' },
  { num: '06', title: 'How Cultures Misread Each Other in Australia', blurb: 'Australia as a collision point for incompatible social software — and what happens when nobody notices.', titleJa: 'オーストラリアにおける文化の誤読', blurbJa: '相容れない社会的ソフトウェアの衝突点としてのオーストラリア——誰も気づかないと何が起きるか。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'cultures-misread-australia', image: '/images/articles/cultures-misread-australia.jpeg' },
  { num: '07', title: 'East vs West: Different Kinds of Tough', blurb: "Resilience looks different depending on where you were forged. Neither is stronger — they're built for different storms.", titleJa: '東洋と西洋：異なる強さの形', blurbJa: 'どこで鍛えられたかによって、強さの姿は異なる。どちらが優れているわけではなく、異なる嵐のために作られている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'east-vs-west-tough', image: '/images/articles/east-vs-west-tough.png' },
  { num: '08', title: 'Relational Morality vs Principled Morality: Two Ways of Being Good', blurb: 'Is morality about universal rules or about the people in front of you? The answer divides civilisations.', titleJa: '関係的道徳と原則的道徳：二つの善のあり方', blurbJa: '道徳とは普遍的ルールのことか、それとも目の前の人々についてのものか——この答えが文明を分ける。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'relational-vs-principled-morality', image: '/images/articles/relational-vs-principled-morality.png' },
  // SPIRITUALITY & RELIGION
  { num: '09', title: 'Gnosticism and the Demiurge: The Hidden Creation Story', blurb: "What if the God who made the world isn't the highest God? The ancient heresy that still makes uncomfortable sense.", titleJa: 'グノーシス主義とデミウルゴス：隠された創造の物語', blurbJa: '世界を作った神が最高の神でないとしたら？今もなお不穏な意味を持つ古代の異端思想。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'gnosticism-and-the-demiurge', image: '/images/articles/gnosticism-and-the-demiurge.jpeg' },
  { num: '10', title: 'The Gospel of Judas: Was He the Real Hero?', blurb: 'The suppressed gospel that rewrites the most famous betrayal in history.', titleJa: 'ユダの福音書：彼は本当の英雄だったのか', blurbJa: '歴史上最も有名な裏切りを書き換える、抑圧された福音書。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'gospel-of-judas', image: '/images/articles/gospel-of-judas.jpeg' },
  { num: '11', title: 'The Book of Enoch: What the Bible Left Out', blurb: 'Angels who fell for human women, giants who walked the earth, and a cosmology the early church buried.', titleJa: 'エノク書：聖書が省いたもの', blurbJa: '人間の女性に恋した天使、地を歩いた巨人、そして初期教会が埋葬した宇宙論。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'book-of-enoch', image: '/images/articles/book-of-enoch.jpeg' },
  { num: '12', title: 'Is Christianity True? The Historical Case', blurb: 'A fair, serious look at the historical evidence for Christianity — without assuming the answer in advance.', titleJa: 'キリスト教は真実か？歴史的証拠', blurbJa: '答えを先に決めずに、キリスト教の歴史的証拠を公平かつ真剣に検討する。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'is-christianity-true', image: '/images/articles/is-christianity-true.jpeg' },
  { num: '12b', title: 'Is Christianity True? The Philosophical Case', blurb: 'The historical evidence is compelling but not conclusive. This article argues that the ambiguity might be the point — and makes the case for why calibrated evidence is what we should expect.', titleJa: 'キリスト教は真実か？哲学的論証', blurbJa: '歴史的証拠は説得力があるが決定的ではない。この記事は、その曖昧さこそが要点かもしれないと論じ、調整された証拠がなぜ私たちが期待すべきものかを論じる。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'is-christianity-true-2', image: '/images/articles/is-christianity-true-2.png' },
  { num: '13', title: 'Sophia: The Forgotten Feminine Divine', blurb: 'The goddess hidden inside Western monotheism — erased, suppressed, and still there if you know where to look.', titleJa: 'ソフィア：忘れられた女性神', blurbJa: '西洋一神教の内側に隠れた女神——消去され、抑圧され、それでもまだそこにいる。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'sophia-feminine-divine', image: '/images/articles/sophia-feminine-divine.jpeg' },
  { num: '14', title: 'Kensho vs Satori: Two Kinds of Awakening, Two Kinds of History', blurb: 'Zen distinguishes between a glimpse and full realisation. The difference maps onto how entire cultures understand transformation.', titleJa: '見性と悟り：二種類の覚醒、二種類の歴史', blurbJa: '禅は一瞥と完全な悟りを区別する。その違いは、文化全体が変容をどう理解するかに対応する。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'kensho-vs-satori', image: '/images/articles/kensho-vs-satori.jpeg' },
  // ORIGINAL THEORIES
  { num: '15', title: 'Yin-Yang as a Fractal Map of the World', blurb: "The ancient symbol isn't just about balance. It's a recursive model of how everything contains its opposite.", titleJa: '陰陽：世界のフラクタル地図として', blurbJa: 'あの古代の象徴は単なるバランスではない。あらゆるものが対立を内包するという再帰的モデルだ。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'yin-yang-fractal-map', image: '/images/articles/yin-yang-fractal-map.png' },
  { num: '16', title: 'Fusion: A Theory of How Civilisations Evolve', blurb: 'An original framework for understanding how cultures absorb, resist, and transform under contact with each other.', titleJa: '融合論：文明の進化についての理論', blurbJa: '文化が互いに接触する中でいかに吸収し、抵抗し、変容するかを理解するための独自フレームワーク。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'fusion-theory', image: '/images/articles/fusion-theory.jpeg' },
  { num: '17', title: 'Uncertainty as Power: Why Not Knowing Is a Strategic Strength', blurb: 'The world rewards those who pretend to certainty. But the deepest strategic advantage may lie in the opposite direction.', titleJa: '不確実性という力：知らないことが戦略的強みになる理由', blurbJa: '世界は確実性を装う人を報いる。しかし最も深い戦略的優位は逆方向にあるかもしれない。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'uncertainty-as-power', image: '/images/articles/uncertainty-as-power.jpeg' },
  { num: '18', title: "Humanity as the Galaxy's Ungovernable Wild Card", blurb: "Why Earth's chaos, contradiction, and refusal to optimise might be our most important trait in a cosmic context.", titleJa: '銀河の制御不能なワイルドカードとしての人類', blurbJa: '地球の混沌、矛盾、そして最適化への拒否が、宇宙的文脈で最も重要な特質かもしれない理由。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'humanity-wild-card', image: '/images/articles/humanity-wild-card.jpeg' },
  { num: '19', title: 'How the Sage Digests the World: A Model of Meaning-Making', blurb: 'A framework for how wisdom traditions absorb experience — and why most people skip the most important step.', titleJa: '賢者はいかに世界を消化するか：意味形成のモデル', blurbJa: '知恵の伝統が経験をいかに吸収するか——そしてなぜほとんどの人が最も重要なステップを飛ばすのか。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'sage-digests-the-world', image: '/images/articles/sage-digests-the-world.jpeg' },
  // HISTORY & MYTHOLOGY
  { num: '20', title: 'Queen Himiko and the Mystery of Yamatai', blurb: "Japan's first ruler was a shaman queen who vanished from the historical record. What really happened?", titleJa: '卑弥呼と邪馬台国の謎', blurbJa: '日本最初の支配者はシャーマン女王だったが、歴史の記録から消えた。本当に何が起きたのか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'queen-himiko-yamatai', image: '/images/articles/queen-himiko-yamatai.jpeg' },
  { num: '21', title: "Amaterasu and Susanoo: Japan's Creation Myths Decoded", blurb: "The sun goddess and the storm god aren't just myths — they encode Japan's deepest tensions about order and chaos.", titleJa: '天照大神とスサノオ：日本の創造神話の解読', blurbJa: '太陽の女神と嵐の神は単なる神話ではない——秩序と混沌についての日本の最も深い緊張を符号化している。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'amaterasu-and-susanoo', image: '/images/articles/amaterasu-and-susanoo.jpeg' },
  { num: '22', title: 'Did a Chinese Immortality-Seeker Found Japan?', blurb: 'The strange legend of Xu Fu — the man who sailed east looking for eternal life and may never have returned.', titleJa: '中国の不死探求者が日本を建国したのか', blurbJa: '東へ向けて永遠の命を求めて航海し、二度と戻らなかったかもしれない男——徐福の奇妙な伝説。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'xu-fu-founded-japan', image: '/images/articles/xu-fu-founded-japan.jpeg' },
  { num: '23', title: 'Fukuzawa Yukichi: The Man on the Banknote', blurb: "Japan's most celebrated Meiji intellectual introduced Western liberty and independence to a modernising nation. His face is on the currency. His argument was buried.", titleJa: '福澤諭吉：紙幣の男', blurbJa: '日本でもっとも称えられた明治の知識人は、近代化する国家に西洋の自由と独立を紹介した。顔は紙幣にある。論拠は埋葬された。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-1-who-he-was', image: '/images/articles/fukuzawa-yukichi.png' },
  { num: '23b', title: 'Fukuzawa Yukichi: The Warning', blurb: "His famous essay on leaving Asia is what Japan remembered. The deeper argument — that obedient minds cannot sustain a free nation — is what Japan forgot.", titleJa: '福澤諭吉：警告', blurbJa: '脱亜論は日本が記憶したものだ。より深い論拠——服従する精神は自由な国家を維持できない——が日本が忘れたものだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-2-the-warning', image: '/images/articles/fukuzawa-2-the-warning.jpeg' },
  { num: '23c', title: 'Fukuzawa Yukichi: Tokugawa Psychology', blurb: "Tokugawa Japan had a tradition of remonstrance — loyal retainers could tell their lords they were wrong. Fukuzawa saw exactly why that wasn't enough.", titleJa: '福澤諭吉：徳川の心理', blurbJa: '徳川日本には諫言の伝統があった。忠実な家臣は主君に誤りを伝えられた。福澤はなぜそれで不十分かを正確に見抜いた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-3-tokugawa-psychology', image: '/images/articles/fukuzawa-3-tokugawa-psychology.jpeg' },
  { num: '23d', title: 'Fukuzawa Yukichi: He Saw It Happening', blurb: "Fukuzawa lived until 1901 — long enough to watch the Meiji project be captured by exactly the compliance architecture he had warned against.", titleJa: '福澤諭吉：それが起きるのを見た', blurbJa: '福澤は1901年まで生きた。明治プロジェクトが彼が警告した服従のアーキテクチャに乗っ取られるのを見るのに十分な時間だった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-4-he-saw-it-happening', image: '/images/articles/fukuzawa-4-he-saw-it-happening.jpeg' },
  { num: '23e', title: 'Fukuzawa Yukichi: How Japan Buried Him', blurb: "Japan honoured Fukuzawa grandly — his face on the banknote, his name on the university. The mechanism for honouring him was also the mechanism for neutralising him.", titleJa: '福澤諭吉：日本はいかに彼を埋葬したか', blurbJa: '日本は福澤を壮大に称えた——顔は紙幣に、名前は大学に。彼を称えるメカニズムはまた、彼を無力化するメカニズムでもあった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-5-memorialisation', image: '/images/articles/fukuzawa-5-memorialisation.png' },
  // SCIENCE & MIND
  { num: '24', title: 'Yamanaka Factors: Can We Reverse Ageing?', blurb: 'The Nobel Prize-winning discovery that cells can be reprogrammed — and what it might mean for the human lifespan.', titleJa: '山中因子：老化を逆転できるか', blurbJa: 'ノーベル賞受賞の発見——細胞は再プログラムできる。それが人間の寿命に何を意味するか。', category: 'science', categoryLabel: 'Science & Mind', categoryLabelJa: '科学・思想', slug: 'yamanaka-factors-ageing', image: '/images/articles/yamanaka-factors-ageing.jpeg' },
  { num: '25', title: 'The Simulation Hypothesis: How Seriously Should We Take It?', blurb: "Nick Bostrom's argument is logically airtight. That doesn't mean the conclusion isn't disturbing.", titleJa: 'シミュレーション仮説：どこまで真剣に考えるべきか', blurbJa: 'ニック・ボストロムの論証は論理的に隙がない。だからといって結論が不穏でないわけではない。', category: 'science', categoryLabel: 'Science & Mind', categoryLabelJa: '科学・思想', slug: 'simulation-hypothesis', image: '/images/articles/simulation-hypothesis.jpeg' },
  // JAPAN & CULTURE
  { num: '26', title: 'The Harmony Paradox: How Cultures That Suppress Small Conflicts Produce Catastrophic Ones', blurb: 'A culture of harmony sounds safer. The historical record suggests the opposite.', titleJa: '調和のパラドックス：小さな衝突を抑圧する文化が大きな破局を生む理由', blurbJa: '調和の文化は安全に聞こえる。しかし歴史の記録はその逆を示唆している。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'harmony-paradox', image: '/images/articles/harmony-paradox.jpeg' },
  { num: '27', title: 'The Emergency That Never Ended: How Temporary Crises Become Permanent Cultures', blurb: "Japan's Meiji leaders said the emergency measures were temporary. They weren't. The pattern is everywhere.", titleJa: '終わらない緊急事態：一時的な危機が永続的な文化になる方法', blurbJa: '明治のリーダーは緊急措置は一時的だと言った。そうではなかった。このパターンはどこにでもある。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'emergency-that-never-ended', image: '/images/articles/emergency-that-never-ended.jpeg' },
  { num: '28', title: "Reading the Air: Japan's Invisible Legal System", blurb: "Japan's real rules aren't written down. They're in the air — and the enforcement is social, not institutional.", titleJa: '空気を読む：日本の見えない法体系', blurbJa: '日本の本当のルールは書かれていない。それは空気の中にある——そして執行は制度的ではなく社会的だ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'reading-the-air', image: '/images/articles/reading-the-air.jpeg' },
  { num: '30', title: 'Survival Mode vs Thriving Mode: The Two Moral Operating Systems', blurb: 'Most ethical disagreements are really about time horizons. Two modes of morality, both internally coherent, producing very different behaviour.', titleJa: 'サバイバルモードと繁栄モード：二つの道徳的オペレーティングシステム', blurbJa: 'ほとんどの倫理的対立は実際には時間軸の問題だ。どちらも内部的に一貫した二つの道徳モードが、非常に異なる行動を生む。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'survival-mode-vs-thriving-mode', image: '/images/articles/survival-mode-vs-thriving-mode.jpeg' },
  { num: '31', title: 'False Coherence: How Individuals and Societies Learn to Lie to Themselves', blurb: 'The story we tell to preserve our self-image. How it starts as a coping mechanism and ends as a liability.', titleJa: '偽りの一貫性：個人と社会が自分自身に嘘をつく方法', blurbJa: '自己イメージを守るために語る物語。コーピングメカニズムとして始まり、負債として終わる。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'false-coherence', image: '/images/articles/false-coherence.jpeg' },
  { num: '32', title: 'Why Free People Make Others Uncomfortable', blurb: "It's not what you've done. It's the question your existence silently asks: was the cost they paid actually necessary?", titleJa: '自由な人がなぜ他者を不快にするのか', blurbJa: 'あなたが何をしたかではない。あなたの存在が静かに問いかけることだ：彼らが払った代償は本当に必要だったのか？', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'why-free-people-make-others-uncomfortable', image: '/images/articles/why-free-people-make-others-uncomfortable.jpeg' },
  { num: '33', title: 'How Rules Stop Being Rules and Start Being Morality', blurb: 'Rules start as practical solutions. Then the context changes, but the rule stays — and somewhere it stops being a rule and becomes a moral truth.', titleJa: 'ルールがルールでなくなり道徳になる方法', blurbJa: 'ルールは実用的な解決策として始まる。やがて文脈が変わるがルールは残る——そしてどこかでルールでなく道徳的真実になる。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'how-rules-become-morality', image: '/images/articles/how-rules-become-morality.jpeg' },
  // JAPAN'S SOCIAL MAP SERIES
  { num: '34', title: "Japan's Two Standards of Truth: Tatemae and Honne", blurb: 'Japan has an official position and a practical reality. Both are real. Neither is exactly a lie. Navigating the gap is a basic social skill — and the entry point to understanding how Japan actually works.', titleJa: '日本の二つの真実の基準：建前と本音', blurbJa: '日本には公式の立場と実際の現実がある。両方とも本物だ。どちらも厳密には嘘ではない。その隙間を渡ることが基本的な社会的スキルだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'tatemae-and-honne', image: '/images/articles/tatemae-and-honne.jpeg' },
  { num: '34b', title: "Japan's Social Map: Uchi and Soto", blurb: "Every culture distinguishes insiders from outsiders. Japan's version is unusually conscious, unusually graduated, and unusually consequential — shaping language, behaviour, and moral obligation at every level of social life.", titleJa: '日本の社会地図：内と外', blurbJa: 'どの文化も内側と外側を区別する。日本版は異例なほど意識的で、異例なほど段階的で、異例なほど重大——言語、行動、道徳的義務をあらゆる社会生活レベルで形成する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'uchi-and-soto', image: '/images/articles/uchi-and-soto.png' },
  { num: '34c', title: "Japan's Social Map: The Rings", blurb: "In Western ethics, every person has equal moral standing. In Japan's traditional architecture, morality is concentric — and where someone sits in your rings determines not just how much you care, but what kind of treatment is even appropriate.", titleJa: '日本の社会地図：環', blurbJa: '西洋倫理では、すべての人が平等な道徳的地位を持つ。日本の伝統的な構造では、道徳は同心円状——誰があなたの環のどこに座るかが、どれほど気にかけるかだけでなく、どんな扱いが適切かさえも決定する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-rings', image: '/images/articles/the-rings.jpeg' },
  { num: '34d', title: "Japan's Social Map: The Ranking", blurb: "Uchi and soto tell you where someone sits relative to you. But within soto, Japan operates a second axis — status — that determines whether an outsider receives deference, indifference, or something darker.", titleJa: '日本の社会地図：ランキング', blurbJa: '内と外はあなたとの相対的な位置を示す。しかし外の中で、日本は第二の軸——地位——を運用する。それが部外者が敬意、無関心、あるいはより暗いものを受けるかを決定する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-ranking', image: '/images/articles/the-ranking.png' },
  // JAPAN'S TWO STANDARDS OF TRUTH SERIES
  { num: '34e', title: "Japan's Two Standards of Truth: The Craftsman and the Diplomat", blurb: 'Japan has a rigorous relationship with physical truth and a managed relationship with social truth. Understanding the difference changes everything.', titleJa: '日本の二つの真実の基準：職人と外交官', blurbJa: '日本は物理的真実に対して厳格で、社会的真実に対して管理された関係を持つ。その違いを理解することがすべてを変える。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-1-dual-epistemology', image: '/images/articles/anti-kaizen-1-dual-epistemology.png' },
  { num: '34f', title: "Japan's Two Standards of Truth: How the Feedback Loop Was Built — And Who Broke It", blurb: "Japan's managed relationship with social truth is not an ancient cultural essence. Edo Japan had functioning correction mechanisms. The Meiji period deliberately dismantled them.", titleJa: '日本の二つの真実の基準：フィードバックループはどのように構築され、誰が壊したのか', blurbJa: '日本の社会的真実との管理された関係は古来の文化的本質ではない。江戸日本には機能する修正メカニズムがあった。明治期がそれを意図的に解体した。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-2-edo-and-meiji', image: '/images/articles/anti-kaizen-2-edo-and-meiji.png' },
  { num: '34g', title: "Japan's Two Standards of Truth: The Falsification Apparatus", blurb: "The military period didn't just commit atrocities and conceal them. It built administrative systems to make honest accounting structurally impossible — in real time.", titleJa: '日本の二つの真実の基準：偽造装置', blurbJa: '軍事期は残虐行為を犯して隠蔽しただけではない。リアルタイムで誠実な説明を構造的に不可能にする行政システムを構築した。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-3-falsification-apparatus', image: '/images/articles/anti-kaizen-3-falsification-apparatus.jpeg' },
  { num: '34h', title: "Japan's Two Standards of Truth: Falsified Inspection Records", blurb: "Fukushima proved what happens when Japan's social-domain truth standard invades physical reality. The same standard has been applied to history for eighty years.", titleJa: '日本の二つの真実の基準：偽造された検査記録', blurbJa: '福島は日本の社会領域の真実基準が物理的現実に侵入するとどうなるかを証明した。同じ基準が八十年間歴史に適用されてきた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-4-inspection-records', image: '/images/articles/anti-kaizen-4-inspection-records.png' },
  { num: '34i', title: "Japan's Two Standards of Truth: The Ghost in the System", blurb: "The nationalist says nations are not machines. He's right — but wrong about what follows. Japan has performed radical social kaizen before.", titleJa: '日本の二つの真実の基準：システムの中の亡霊', blurbJa: '国家主義者は国家は機械ではないと言う。彼は正しい——しかしその後に続くことについては間違っている。日本は以前にも根本的な社会改善を行った。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-5-ghost-in-the-system', image: '/images/articles/anti-kaizen-5-ghost-in-the-system.png' },
  // JAPAN'S RELATIONSHIP WITH NEGATIVITY SERIES
  { num: '35', title: "Japan's Relationship with Negativity: Kotodama", blurb: 'In Japan, words are not just descriptions of reality. They participate in creating it. This ancient belief shapes everyday language — and runs directly against the kind of honest negative expression that reckoning requires.', titleJa: '日本とネガティビティの関係：言霊', blurbJa: '日本では、言葉は単なる現実の描写ではない。言葉は現実の創造に参加する。この古来の信念が日常言語を形成し、和解が必要とする誠実な否定的表現と対立する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-1-kotodama', image: '/images/articles/negativity-1-kotodama.jpeg' },
  { num: '35b', title: "Japan's Relationship with Negativity: Gambaru and Shikata ga Nai", blurb: "Push through. Then accept and move on. Japan's two-part response to hardship is genuinely admirable — and leaves no room for the middle space where reckoning lives.", titleJa: '日本とネガティビティの関係：頑張ると仕方がない', blurbJa: '乗り越えよ。次に受け入れて前に進む。困難への日本の二段階の反応は真に称賛すべきだ——そして和解が生きる中間の空間に余地を残さない。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-2-gambaru', image: '/images/articles/negativity-2-gambaru.jpeg' },
  { num: '35c', title: "Japan's Relationship with Negativity: The Smooth Surface", blurb: "In Japan, expressing negative inner states isn't just personally uncomfortable — it imposes an unwanted burden on everyone present. The social surface must be kept smooth.", titleJa: '日本とネガティビティの関係：滑らかな表面', blurbJa: '日本では、否定的な内的状態を表現することは単に個人的に不快なだけでなく、場にいる全員に望まれない負担を課す。社会的表面は滑らかに保たれなければならない。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-3-smooth-surface', image: '/images/articles/negativity-3-smooth-surface.png' },
  { num: '35d', title: "Japan's Relationship with Negativity: The Cost", blurb: "The cultural architecture that keeps Japan's social surface smooth carries a price — stigma, somatisation, and silence for individuals; a collective inability to sit with difficult reality for the nation.", titleJa: '日本とネガティビティの関係：コスト', blurbJa: '日本の社会的表面を滑らかに保つ文化的アーキテクチャには代価がある——個人にはスティグマ、身体化、沈黙を。国家には困難な現実に座り込む集団的な無能力を。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-4-the-cost', image: '/images/articles/negativity-4-the-cost.jpeg' },
  // WHAT HUMOUR ACTUALLY IS SERIES
  { num: '36', title: 'What Humour Actually Is: The Structure of the Joke', blurb: 'Humor exists wherever anxiety exists. The laugh lives in the gap between violation and safety — which makes comedy one of the most honest windows into any culture.', titleJa: 'ユーモアとは実際何か：ジョークの構造', blurbJa: 'ユーモアは不安があるところにしか存在しない。笑いは違反と安全の間の隙間に宿る——つまりコメディはどんな文化への最も誠実な窓の一つだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'what-humor-actually-is', image: '/images/articles/what-humor-actually-is.png' },
  { num: '36b', title: 'What Humour Actually Is: Japanese Comedy and Restored Order', blurb: 'Manzai has a boke who disrupts and a tsukkomi who corrects. The laugh is in the restoration. This tells you exactly what Japan is most afraid of.', titleJa: 'ユーモアとは実際何か：日本のコメディと秩序の回復', blurbJa: '漫才にはボケとツッコミがいる。笑いは回復にある。これは日本が最も恐れているものを正確に教えてくれる。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'japan-comedy-restored-order', image: '/images/articles/japan-comedy-restored-order.png' },
  { num: '36c', title: "What Humour Actually Is: The West's Many Anxieties", blurb: 'American, British, Australian, Irish — each comic culture is a precise map of what its people feared most and found a way, through laughter, to survive.', titleJa: 'ユーモアとは実際何か：西洋の多くの不安', blurbJa: 'アメリカ、イギリス、オーストラリア、アイルランド——それぞれのコメディ文化は、その人々が最も恐れ、笑いを通じて生き延びた方法の正確な地図だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'the-wests-many-anxieties', image: '/images/articles/the-wests-many-anxieties.png' },
  { num: '36d', title: 'What Humour Actually Is: Banter', blurb: "Banter is flyting's informal descendant — ritualized insult as a language of closeness. The line between banter and bullying is not the words used but whether both parties feel safe enough to return fire.", titleJa: 'ユーモアとは実際何か：バンター', blurbJa: 'バンターはフライティングの非公式な子孫——親密さの言語としての儀式化された侮辱だ。バンターといじめの境界線は使われた言葉ではなく、両者が反撃できるほど安全だと感じているかどうかだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'banter', image: '/images/articles/banter.png' },
  // THE AUSTRALIAN SOCIAL SCRIPT SERIES
  { num: '37', title: 'The Australian Social Script: The Friendliness Mandate', blurb: "In Australia, warmth isn't optional. It's a performance requirement. And the people who pay the highest price are those whose natural register doesn't match the script.", titleJa: 'オーストラリアの社会スクリプト：友好性の義務', blurbJa: 'オーストラリアでは、温かさは任意ではない。それはパフォーマンスの要件だ。最も高い代価を払うのは、自然なレジスターがスクリプトに合わない人々だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'friendliness-mandate', image: '/images/articles/friendliness-mandate.jpeg' },
  { num: '37b', title: 'The Australian Social Script: Why Australia Learned to Test Strangers', blurb: 'The frontier. The convicts. The horizontal trust built when vertical trust had failed. Australian banter was never just friendliness — it was a diagnostic.', titleJa: 'オーストラリアの社会スクリプト：なぜオーストラリアは見知らぬ人を試すことを学んだのか', blurbJa: 'フロンティア、囚人、垂直的信頼が失われたときに構築された水平的信頼。オーストラリアのバンターは単なる友好性ではなかった——それは診断だった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'why-australia-tests-strangers', image: '/images/articles/why-australia-tests-strangers.jpeg' },
  { num: '37c', title: 'The Australian Social Script: The Ghost of the Frontier', blurb: "The frontier is gone. The social technology it produced is not. Australia is still running a threat-detection system calibrated for conditions that haven't existed for over a century.", titleJa: 'オーストラリアの社会スクリプト：フロンティアの亡霊', blurbJa: 'フロンティアは消えた。それが生み出した社会的技術は消えていない。オーストラリアは一世紀以上前に消えた状況に合わせて調整された脅威検知システムをまだ動かしている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'ghost-of-the-frontier', image: '/images/articles/ghost-of-the-frontier.jpeg' },
  // SEKIGAHARA SERIES
  { num: '38', title: 'Sekigahara: The Man on the Hill', blurb: "In the autumn of 1600, one young man's hesitation changed the course of Japanese civilisation.", titleJa: '関ヶ原：丘の上の男', blurbJa: '1600年の秋、一人の若者の躊躇が日本文明の行方を変えた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-1-the-man-on-the-hill', image: '/images/articles/sekigahara-1-the-man-on-the-hill.png' },
  { num: '38b', title: 'Sekigahara: The Japan That Never Was', blurb: "Hideaki's betrayal handed Ieyasu victory. But it was closer than history remembers — and the alternative Japan was not a fantasy.", titleJa: '関ヶ原：あり得た日本', blurbJa: '秀秋の裏切りが家康に勝利をもたらした。しかし歴史が記憶するより僅差だった——そして別の日本は幻想ではなかった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-2-the-japan-that-never-was', image: '/images/articles/sekigahara-2-the-japan-that-never-was.png' },
  { num: '38c', title: 'Sekigahara: The Machinery of Harmony', blurb: 'The stillness of Edo Japan was not a reflection of the people. The people were a reflection of the stillness.', titleJa: '関ヶ原：調和の機械', blurbJa: '江戸日本の静けさは人々の反映ではなかった。人々が静けさの反映だったのだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-3-the-machinery-of-harmony', image: '/images/articles/sekigahara-3-the-machinery-of-harmony.png' },
  { num: '38d', title: 'Sekigahara: A Different People', blurb: 'Remove the Tokugawa crucible and you get a recognisably Japanese people — but differently so.', titleJa: '関ヶ原：異なる人々', blurbJa: '徳川の坩堝を取り除けば、確かに日本人とわかる人々が得られる——しかし異なる形で。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-4-a-different-people', image: '/images/articles/sekigahara-4-a-different-people.jpeg' },
  { num: '38e', title: "Sekigahara: Variables, Not Constants", blurb: "Japan's institutional struggles are not destiny. They are history. And history can be changed.", titleJa: '関ヶ原：定数ではなく変数', blurbJa: '日本の制度的苦闘は運命ではない。それは歴史だ。そして歴史は変えられる。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-5-variables-not-constants', image: '/images/articles/sekigahara-5-variables-not-constants.png' },
  // THE INVISIBLE MAN SERIES
  { num: '39', title: "The Invisible Man: The Present Reality", blurb: "Asian men receive disproportionately low interest from non-Asian women in Western countries. Most people have noticed. Few discuss it directly.", titleJa: '見えない男：現在の現実', blurbJa: 'アジア系男性は西洋諸国で非アジア系女性から不釣り合いに低い関心しか受けない。ほとんどの人が気づいている。直接議論する人は少ない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-1-the-present-reality', image: '/images/articles/invisible-man-1-the-present-reality.png' },
  { num: '39b', title: "The Invisible Man: What Makes a Man Attractive", blurb: "Most people never question what they find attractive. It feels instinctive — almost biological. But spend time looking across cultures and that certainty starts to loosen.", titleJa: '見えない男：男性の魅力とは何か', blurbJa: 'ほとんどの人は自分が魅力的だと思うものを疑問視しない。本能的に、ほぼ生物学的に感じられる。しかし文化を越えて眺め始めると、その確信が緩み始める。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-2-what-makes-a-man-attractive', image: '/images/articles/invisible-man-2-what-makes-a-man-attractive.jpeg' },
  { num: '39c', title: "The Invisible Man: When Sensitivity Was Strength", blurb: "In the early 19th century, the most admired men in the Western world were poets — celebrated for emotional depth, aesthetic sensitivity, and the ability to articulate inner experience.", titleJa: '見えない男：感受性が強さだった時代', blurbJa: '19世紀初頭、西洋世界で最も尊敬された男性は詩人たちだった——感情の深さ、美的感受性、内なる経験を表現する能力で称えられた。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-3-when-sensitivity-was-strength', image: '/images/articles/invisible-man-3-when-sensitivity-was-strength.jpeg' },
  { num: '39d', title: "The Invisible Man: The Making of the Hard Man", blurb: "The Romantic ideal did not fade gradually. It was dismantled — quickly, deliberately, and for reasons that had little to do with what men are naturally like.", titleJa: '見えない男：硬い男の形成', blurbJa: 'ロマン主義の理想は徐々に消えたのではない。解体された——迅速に、意図的に、そして男性の本来の姿とはほとんど関係のない理由で。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-4-the-making-of-the-hard-man', image: '/images/articles/invisible-man-4-the-making-of-the-hard-man.png' },
  { num: '39e', title: "The Invisible Man: The Gold Rush", blurb: "In 1851 gold was discovered in Victoria. Within months tens of thousands of men from around the world had descended on regional Australia — and the masculine template that emerged would shape the culture for generations.", titleJa: '見えない男：ゴールドラッシュ', blurbJa: '1851年、ビクトリアで金が発見された。数ヶ月のうちに世界中から何万人もの男性がオーストラリア地方に押し寄せ——生まれた男性像は何世代にもわたって文化を形成することになった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-5-the-gold-rush', image: '/images/articles/invisible-man-5-the-gold-rush.png' },
  { num: '39f', title: "The Invisible Man: Different Environments, Different Men", blurb: "The differences between Eastern and Western masculine ideals did not appear suddenly in history. They have roots that go back to the fundamental conditions in which these civilisations developed.", titleJa: '見えない男：異なる環境、異なる男性', blurbJa: '東西の男性的理想の違いは歴史の中で突然現れたのではない。それらは文明が発展した基本的な条件にまで遡る根を持っている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-6-different-environments-different-men', image: '/images/articles/invisible-man-6-different-environments-different-men.png' },
  { num: '39g', title: "The Invisible Man: Did Beauty Shape the Face", blurb: "A hypothesis worth asking: if masculine ideals vary by culture and those ideals shape what people find attractive, could centuries of different selection pressures have produced measurable differences in physical appearance?", titleJa: '見えない男：美が顔を形成したのか', blurbJa: '問う価値のある仮説：男性的理想が文化によって異なり、それらの理想が人々が魅力的だと思うものを形成するなら、何世紀もの異なる選択圧力が外見に測定可能な違いをもたらした可能性はあるか。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-7-did-beauty-shape-the-face', image: '/images/articles/invisible-man-7-did-beauty-shape-the-face.png' },
  { num: '39h', title: "The Invisible Man: The Man Without a Love Interest", blurb: "When Bruce Lee became an international star in the early 1970s, he was arguably the most physically compelling action hero on screen. He almost never kissed anyone on screen.", titleJa: '見えない男：恋愛対象のない男', blurbJa: 'ブルース・リーが1970年代初頭に国際的スターになったとき、彼はおそらくスクリーン上で最も肉体的に魅力的なアクションヒーローだった。彼はスクリーン上でほとんど誰ともキスしなかった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-8-the-man-without-a-love-interest', image: '/images/articles/invisible-man-8-the-man-without-a-love-interest.png' },
  { num: '39i', title: "The Invisible Man: The State Decides", blurb: "In 2021 China's broadcasting authority banned overly feminine male celebrities from national media. The term used was niang pao — girly or effeminate. The message was direct: this aesthetic had no place in the national landscape.", titleJa: '見えない男：国家が決める', blurbJa: '2021年、中国の放送当局は過度に女性的な男性有名人を国家メディアから禁止した。使われた用語は娘炮——女らしいまたは軟弱。メッセージは直接的だった：このような美学に国家の景観に居場所はないと。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-9-the-state-decides', image: '/images/articles/invisible-man-9-the-state-decides.png' },
  { num: '39j', title: "The Invisible Man: K-pop and Its Limits", blurb: "For the first time in living memory a male aesthetic originating in East Asia built mass appeal in the West entirely on its own terms. BTS filled stadiums across America and Europe. But the limits of that breakthrough matter as much as the breakthrough itself.", titleJa: '見えない男：K-POPとその限界', blurbJa: '生きた記憶の中で初めて、東アジア発祥の男性的美学が完全に独自の条件で西洋で大衆的な支持を得た。BTSはアメリカとヨーロッパ中のスタジアムを満員にした。しかしその突破口の限界は突破口そのものと同様に重要だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-10-kpop-and-its-limits', image: '/images/articles/invisible-man-10-kpop-and-its-limits.png' },
  { num: '39k', title: "The Invisible Man: Why He Was Never in the Picture", blurb: "This series began with a measurable fact. It ends with an explanation — not a simple one, but the accumulated residue of several distinct historical forces, each reinforcing the last.", titleJa: '見えない男：なぜ彼は決して写真に写らなかったのか', blurbJa: 'このシリーズは測定可能な事実から始まった。単純ではない説明で終わる——いくつかの異なる歴史的力の蓄積された残留物、それぞれが次を強化している。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-11-why-he-was-never-in-the-picture', image: '/images/articles/invisible-man-11-why-he-was-never-in-the-picture.jpeg' },
  // TO BE JAPANESE SERIES
  { num: '40', title: 'To Be Japanese: The Weight of the Identification', blurb: 'When a Japanese person says "I am Japanese" it carries something closer to an ontological claim. This series asks why — and what it costs.', titleJa: '日本人であること：帰属のある重さ', blurbJa: '日本人が「私は日本人だ」と言うとき、それは存在論的な主張に近い何かを帯びている。このシリーズはその理由と、それが何を代償とするかを問う。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'to-be-japanese', image: '/images/articles/to-be-japanese.jpeg' },
  { num: '40b', title: 'To Be Japanese: Why the Fusion Runs So Deep', blurb: 'For national identity to become as total as it did in Japan, several things had to happen simultaneously — geography, religion, language, and deliberate policy all pushing in the same direction.', titleJa: '日本人であること：融合がこれほど深く根付いた理由', blurbJa: '日本のナショナルアイデンティティがこれほど全体的なものになるには、いくつかのことが同時に起きなければならなかった——地理、宗教、言語、そして意図的な政策がすべて同じ方向に向かって。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'why-the-fusion-runs-so-deep', image: '/images/articles/why-the-fusion-runs-so-deep.png' },
  { num: '40c', title: 'To Be Japanese: Written in the Blood', blurb: "From the 1960s through the 1980s, a genre emerged in Japan claiming that Japaneseness wasn't merely cultural — it was biological. This is where that idea came from, and what it cost.", titleJa: '日本人であること：血に刻まれたもの', blurbJa: '1960年代から80年代にかけて、日本人であることは文化的なものだけでなく生物学的なものだと主張するジャンルが生まれた。その思想がどこから来て、何を代償としたか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'written-in-the-blood', image: '/images/articles/written-in-the-blood.png' },
  { num: '40d', title: 'To Be Japanese: What Reckoning Actually Costs', blurb: 'Imagine a Japanese person who arrives at a genuine personal reckoning with the war. What does that moment actually cost them — not politically, but personally?', titleJa: '日本人であること：清算が実際に何を代償とするか', blurbJa: '戦争について真の個人的な清算に至った日本人を想像してほしい。その瞬間は彼らに何を——政治的にではなく、個人的に——代償として課すのか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'what-reckoning-actually-costs', image: '/images/articles/what-reckoning-actually-costs.png' },
  // CULTURE CREATES THE FUTURE
  { num: '41', title: 'Culture Creates the Future: Why Culture Determines Your Economy', blurb: 'Economists explain national wealth through resources, labour costs, and geography. But comparative advantage is psychological before it is material — and the soil determines what grows.', titleJa: '文化が未来を作る：なぜ文化は経済を決定するのか', blurbJa: '経済学者は資源、労働コスト、地理によって国家の富を説明する。しかし比較優位は物質的である前に心理的だ——そして土壌が何が育つかを決める。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-01-cultural-comparative-advantage', image: '/images/articles/culture-creates-the-future-01-cultural-comparative-advantage.jpeg' },
  { num: '41b', title: 'Culture Creates the Future: How Automation Sharpens the Divide', blurb: 'Automation does not affect sea and floodplain civilisations equally. What gets compressed first, what remains, and what sharpens — the cultural dimension most analysis misses.', titleJa: '文化が未来を作る：自動化が分断をどのように鋭化するか', blurbJa: '自動化は海洋文明と氾濫原文明に等しく影響しない。最初に圧縮されるもの、残るもの、鋭化されるもの——ほとんどの分析が見逃す文化的次元。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-02-automation-sharpens-the-divide', image: '/images/articles/culture-creates-the-future-02-automation-sharpens-the-divide.png' },
  { num: '41c', title: 'Culture Creates the Future: Two Nations, Two Strategies, Two Futures', blurb: 'Japan and Australia as embodiments of opposite responses to the same civilisational moment. One chose the lower floor and the lower ceiling. The other is living with the consequences of having chosen neither.', titleJa: '文化が未来を作る：二つの国家、二つの戦略、二つの未来', blurbJa: '同じ文明的瞬間への反対の反応を体現する日本とオーストラリア。一方は低い床と低い天井を選んだ。もう一方はどちらも選ばなかった結果と共に生きている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-03-two-nations-two-strategies', image: '/images/articles/culture-creates-the-future-03-two-nations-two-strategies.png' },
  { num: '41d', title: "Culture Creates the Future: Australia's Demographic Bet", blurb: "Australia is running a civilisational experiment whose outcome is genuinely uncertain. Floodplain cultural instincts operating inside sea-culture institutions — high variance, extraordinary upside, real downside.", titleJa: '文化が未来を作る：オーストラリアの人口統計的賭け', blurbJa: 'オーストラリアは結果が真に不確実な文明的実験を行っている。海洋文化の制度の中で動く氾濫原の文化的本能——高分散、非凡なアップサイド、本物のダウンサイド。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-04-australias-demographic-bet', image: '/images/articles/culture-creates-the-future-04-australias-demographic-bet.jpeg' },
  { num: '41e', title: 'Culture Creates the Future: The Creator Economy and the Wealth of Worlds', blurb: 'When production cost collapses toward zero, what remains scarce is a distinctive worldview. Japan holds centuries of accumulated aesthetic capital. Australia holds positional hybridity. Neither can be replicated by the other.', titleJa: '文化が未来を作る：クリエイターエコノミーと世界の富', blurbJa: '制作コストがゼロに向かって崩壊するとき、稀少なままのものは独特の世界観だ。日本は何世紀もの蓄積された美的資本を保有する。オーストラリアは位置的なハイブリッド性を。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-05-creator-economy-wealth-of-worlds', image: '/images/articles/culture-creates-the-future-05-creator-economy-wealth-of-worlds.png' },
  { num: '41f', title: 'Culture Creates the Future: Where Creators Go For Inspiration', blurb: 'Japan offers something Singapore structurally cannot — cultural depth accumulated over centuries. Creators do not need to live in Japan permanently to be shaped by it. They need periodic, genuine immersion.', titleJa: '文化が未来を作る：クリエイターはどこにインスピレーションを求めるか', blurbJa: '日本はシンガポールが構造的に提供できないものを提供する——何世紀にもわたって蓄積された文化的深さ。クリエイターはそれによって形成されるために日本に永続的に住む必要はない。定期的な、本物の没入が必要だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-06-where-creators-go-for-inspiration', image: '/images/articles/culture-creates-the-future-06-where-creators-go-for-inspiration.jpeg' },
  { num: '41g', title: 'Culture Creates the Future: Where Creators Actually Live', blurb: 'Inspiration and habitation are different needs. A layered ecosystem — Japan for deep inspiration, Singapore for lean operations, Australia for long-term habitation. No single nation captures everything.', titleJa: '文化が未来を作る：クリエイターが実際に住む場所', blurbJa: 'インスピレーションと居住は異なるニーズだ。層状のエコシステム——深いインスピレーションのための日本、無駄のない運営のためのシンガポール、長期的な居住のためのオーストラリア。どの単一の国家もすべてを獲得しない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-07-where-creators-live', image: '/images/articles/culture-creates-the-future-07-where-creators-live.jpeg' },
  { num: '41h', title: 'Culture Creates the Future: The Individual Universe', blurb: 'When AI makes cinematic production accessible to individuals, the universe model becomes available at the individual level. The hybrid creator — fluent across civilisations, grounded in depth — is the profile this entire moment is selecting for.', titleJa: '文化が未来を作る：個人の宇宙', blurbJa: 'AIが映画的制作を個人に利用可能にするとき、宇宙モデルは個人レベルで利用可能になる。文明にわたって流暢で、深みに根ざしたハイブリッドクリエイター——それがこの瞬間全体が選択しているプロフィールだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-08-the-individual-universe', image: '/images/articles/culture-creates-the-future-08-the-individual-universe.png' },
  { num: '42', title: 'The Whole and the Part: The Cosmological Fork', blurb: 'The date, the address, the name — three mundane conventions, all pointing in the same direction. A difference in assumption so deep it shapes how entire cultures organise time, space, and identity simultaneously.', titleJa: '全体と部分：宇宙論的な分岐点', blurbJa: '日付、住所、名前——三つの平凡な慣習、すべてが同じ方向を指している。文化全体が時間、空間、アイデンティティをどのように組織するかを形成するほど深い前提の違い。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-1-the-cosmological-fork', image: '/images/articles/article-1-the-cosmological-fork.jpeg' },
  { num: '42b', title: 'The Whole and the Part: The Language of Survival', blurb: 'Why indirect communication is not a personality flaw but a cosmological consequence. One culture uncomfortable with disruption, the other with silence — both protecting belonging from opposite directions.', titleJa: '全体と部分：生存の言語', blurbJa: 'なぜ間接的なコミュニケーションは性格の欠点ではなく宇宙論的な帰結なのか。一方の文化は混乱に不快感を覚え、もう一方は沈黙に——両方とも反対方向から帰属を守っている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-2-the-language-of-survival', image: '/images/articles/article-2-the-language-of-survival.png' },
  { num: '42c', title: 'The Whole and the Part: Connection as Assumption', blurb: 'Why one culture thinks relationships need to be built and the other thinks they need to be protected. One cannot name its problems. The other cannot rest inside its relationships.', titleJa: '全体と部分：前提としてのつながり', blurbJa: 'なぜ一方の文化は関係を構築する必要があると考え、もう一方は守る必要があると考えるのか。一方は問題を名付けられない。もう一方は関係の中で休めない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-3-connection-as-assumption', image: '/images/articles/article-3-connection-as-assumption.png' },
  { num: '42d', title: 'The Whole and the Part: Symmetric Insecurities', blurb: 'Neither culture is more evolved — they are just afraid of different things. Both fears are rational responses to their respective cosmologies. Both have institutionalised their anxiety into a very sophisticated survival mode.', titleJa: '全体と部分：対称的な不安', blurbJa: 'どちらの文化もより進化しているわけではない——単に異なるものを恐れているだけだ。両方の恐れはそれぞれの宇宙論への合理的な反応だ。両方が不安を洗練されたサバイバルモードへと制度化した。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-4-symmetric-insecurities', image: '/images/articles/article-4-symmetric-insecurities.png' },
  { num: '42e', title: 'The Whole and the Part: The Structural Solution', blurb: 'What Scandinavia suggests about the relationship between security and communication. Directness, comfort with silence, the ability to surface conflict: not virtues you choose, but capacities that security makes available.', titleJa: '全体と部分：構造的解決策', blurbJa: 'スカンジナビアが安心とコミュニケーションの関係について示唆すること。直接性、沈黙への安心、対立を浮上させる能力——選ぶ美徳ではなく、安心が利用可能にする能力だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-5-the-structural-solution', image: '/images/articles/article-5-the-structural-solution.png' },
  { num: '01', title: 'Why People Think So Different: How Geography and Survival Has Shaped Us', blurb: 'Why do people from different cultures think so differently? Two factors that shaped the contrast between Japan and Australia — the floodplains of China, and the black ships of 1853.', titleJa: 'なぜ人は違う考え方をするのか：地理と生存がどのように私たちを形成したか', blurbJa: '異なる文化の人々はなぜ違う考え方をするのか？日本とオーストラリアの対比を形成した二つの要因——中国の氾濫原と1853年の黒船。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'why-people-think-so-different-1', authored: 'human', image: '/images/articles/why-people-think-so-different-1.png' },
  { num: '01b', title: 'Why People Think So Different: Floodplain and Fractured Sea Cultures', blurb: 'The geography that shaped China created collectivism. The geography that shaped Europe and Japan created competition and hierarchy. And Japan ended up with both.', titleJa: 'なぜ人は違う考え方をするのか：氾濫原文化と分裂海文化', blurbJa: '中国を形成した地形は集団主義を生み出した。ヨーロッパと日本を形成した地形は競争と階層を生み出した。そして日本は両方を持つことになった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'why-people-think-so-different-2', authored: 'human', image: '/images/articles/floodplain-vs-fractured-sea.png' },
  { num: '43c', title: "The Great Illusion: You Went There. You Didn't See It.", blurb: "The traveller moves through two weeks of interfaces and experiences them as the place itself. The Westerner accidentally performs dominance through sheer unawareness. The larger gap stayed where it was.", titleJa: '大いなる幻想：あなたはそこに行った。しかし見えなかった。', blurbJa: '旅行者は二週間のインターフェースを通り抜け、それらをその場所そのものとして経験する。西洋人は純粋な無自覚を通じて支配を偶然演じる。より大きなギャップはそのままそこにあり続けた。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-3-you-went-there-you-didnt-see-it', image: '/images/articles/great-illusion-3-you-went-there-you-didnt-see-it.png' },
  { num: '43', title: "The Great Illusion: The Fish Don't Know They're Wet", blurb: "Most people who grow up in Western countries carry a complete set of assumptions about how human beings work. Not opinions. Assumptions. That feeling is the illusion.", titleJa: '大いなる幻想：魚は自分が濡れていることを知らない', blurbJa: '西洋諸国で育ったほとんどの人は、人間がどのように機能するかについての完全な前提の集合を持っている。意見ではない。前提だ。その感覚こそが幻想だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-1-the-fish-dont-know-theyre-wet', image: '/images/articles/great-illusion-1-the-fish-dont-know-theyre-wet.png' },
  { num: '43g', title: 'The Great Illusion: Why Nobody Told You', blurb: "The illusion doesn't need to be actively maintained. It maintains itself. The pointing finger gets more attention than the water itself. You're in the water. Now you know it's there.", titleJa: '大いなる幻想：なぜ誰も教えてくれなかったのか', blurbJa: '幻想は積極的に維持される必要がない。それは自ら維持される。指差す指が水自体より多くの注意を受ける。あなたは水の中にいる。今あなたはそれがそこにあることを知っている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-7-why-nobody-told-you', image: '/images/articles/great-illusion-7-why-nobody-told-you.jpeg' },
  { num: '43f', title: 'The Great Illusion: The Loop', blurb: "The assumption causes the performance. The performance prevents genuine understanding. The prevention confirms the assumption. Nobody decided any of this. It runs automatically, on both sides, every time.", titleJa: '大いなる幻想：ループ', blurbJa: '前提がパフォーマンスを引き起こす。パフォーマンスが本物の理解を妨げる。妨げが前提を確認する。誰もこれを決めなかった。二つのオペレーティングシステムが出会うたびに、両側で、自動的に動く。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-6-the-loop', image: '/images/articles/great-illusion-6-the-loop.png' },
  { num: '43e', title: 'The Great Illusion: The Man in the Room', blurb: "Descartes stripped away tradition to find pure reason — the most culturally specific move imaginable, understood as universal. There is no view from nowhere. There is only ever a view from somewhere.", titleJa: '大いなる幻想：部屋の中の男', blurbJa: 'デカルトは純粋な理性を見つけるために伝統をはぎ取った——普遍的として理解された、想像できる中で最も文化的に特定の動き。どこでもない視点はない。常にどこかからの視点があるだけだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-5-the-man-in-the-room', image: '/images/articles/great-illusion-5-the-man-in-the-room.png' },
  { num: '43b', title: 'The Great Illusion: The Water Has a Shape', blurb: "The junior employee staying silent in the Japanese meeting isn't being suppressed — they're doing their job correctly. The Western observer's discomfort is an assumption revealing itself.", titleJa: '大いなる幻想：水には形がある', blurbJa: '日本の会議で沈黙している若手社員は抑圧されているのではない——正しく仕事をしているのだ。西洋の観察者の不快感は、自らを明らかにしている前提だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-2-the-water-has-a-shape', image: '/images/articles/great-illusion-2-the-water-has-a-shape.png' },
  { num: '43d', title: 'The Great Illusion: There Is No Single Track', blurb: "The river that gets wide enough starts to look like the landscape itself. Democracy doesn't feel like a Western value. It feels like what free people eventually choose. That's the illusion at its deepest.", titleJa: '大いなる幻想：一本の軌道などない', blurbJa: '十分に広くなった川は景観そのものに見え始める。民主主義は西洋的な価値のように感じられない。自由な人々が最終的に選ぶもののように感じられる。それが最も深いレベルの幻想だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'great-illusion-4-there-is-no-single-track', image: '/images/articles/great-illusion-4-there-is-no-single-track.png' },
  // THE EMPTINESS BEHIND THE EFFORT SERIES
  { num: '44', title: 'The Emptiness Behind the Effort: The Machine That Never Stopped', blurb: 'Walk into any Japanese high school and something will strike you before a single lesson begins. The discipline, the uniforms, the bowing — it has been normal for over 150 years. This is where the machine starts.', titleJa: '努力の背後にある空虚：止まらなかった機械', blurbJa: '日本の高校に足を踏み入れると、授業が始まる前から何かが目につく。規律、制服、礼——それは150年以上にわたって当たり前のことだった。機械はここから始まる。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-01-the-machine-that-never-stopped', image: '/images/articles/the-emptiness-behind-the-effort-01-the-machine-that-never-stopped.png' },
  { num: '44b', title: 'The Emptiness Behind the Effort: The Borrowed Purpose', blurb: 'After 1945, Japan rebuilt itself into the second largest economy in the world within a generation. The machine kept running — but the purpose driving it had been borrowed, not chosen.', titleJa: '努力の背後にある空虚：借り物の目的', blurbJa: '1945年以降、日本は一世代のうちに世界第二位の経済大国へと再建した。機械は動き続けた——しかしそれを駆動する目的は選ばれたものではなく、借り物だった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-02-the-borrowed-purpose', image: '/images/articles/the-emptiness-behind-the-effort-02-the-borrowed-purpose.png' },
  { num: '44c', title: 'The Emptiness Behind the Effort: The Void and the Villain', blurb: 'When a society loses its purpose, it does not announce it. The symptoms appear quietly. In Japan, they were hard to miss — if you knew what you were looking at.', titleJa: '努力の背後にある空虚：空虚と悪役', blurbJa: '社会が目的を失うとき、それを宣言しない。症状は静かに現れる。日本では、それが何であるかを知っていれば、見逃しにくいものだった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-03-the-void-and-the-villain', image: '/images/articles/the-emptiness-behind-the-effort-03-the-void-and-the-villain.png' },
  { num: '44d', title: 'The Emptiness Behind the Effort: The American Trap', blurb: "Why didn't Japan undergo the same psychological reconstruction as Germany after the war? The answer involves a Cold War calculation, a convenient emperor, and a bargain that foreclosed the possibility of genuine reckoning.", titleJa: '努力の背後にある空虚：アメリカの罠', blurbJa: 'なぜ日本は戦後にドイツと同じ心理的再建を経なかったのか？答えは冷戦の計算、都合の良い天皇、そして真の清算の可能性を閉ざした取引にある。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-04-the-american-trap', image: '/images/articles/the-emptiness-behind-the-effort-04-the-american-trap.png' },
  { num: '44e', title: 'The Emptiness Behind the Effort: The Wound Nobody Named', blurb: 'The paranoid nationalism and authoritarian mobilisation that swept East Asia was not inevitable. It was produced — by opium wars, burned palaces, and a century of systematic dismantling by Western powers.', titleJa: '努力の背後にある空虚：誰も名付けなかった傷', blurbJa: '東アジアを席巻した偏執的なナショナリズムと権威主義的動員は必然ではなかった。それは生産されたものだ——アヘン戦争、焼かれた宮殿、西洋列強による一世紀にわたる組織的な解体によって。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-05-the-wound-nobody-named', image: '/images/articles/the-emptiness-behind-the-effort-05-the-wound-nobody-named.png' },
  { num: '44f', title: 'The Emptiness Behind the Effort: The Universal Machine', blurb: "Japan is the subject of this series, but it isn't really the point. The pattern — discipline without meaning, purpose collapsing, the void filling with conformity and the need for a villain — runs in every culture that has demanded sacrifice without guaranteeing meaning.", titleJa: '努力の背後にある空虚：普遍的な機械', blurbJa: 'このシリーズの主題は日本だが、本当の焦点はそこではない。意味なき規律、崩壊する目的、服従と悪役への必要性で埋まる空虚——このパターンは、意味を保証せずに犠牲を求めたあらゆる文化で動いている。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-06-the-universal-machine', image: '/images/articles/the-emptiness-behind-the-effort-06-the-universal-machine.png' },
  { num: '44g', title: 'The Emptiness Behind the Effort: The Machine Can Stop', blurb: "If the pattern has a solution, it isn't complicated. It doesn't require a political movement or a new ideology. It starts with a single honest question: why did we build this in the first place?", titleJa: '努力の背後にある空虚：機械は止まれる', blurbJa: 'このパターンに解決策があるとすれば、それは複雑なものではない。政治運動も新しいイデオロギーも必要ない。一つの誠実な問いから始まる——そもそもなぜこれを作ったのか？', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-emptiness-behind-the-effort-07-the-machine-can-stop', image: '/images/articles/the-emptiness-behind-the-effort-07-the-machine-can-stop.png' },
  // TRISKELION — Book I: Reading the Kojiki
  { num: 'T-01', title: "Reading the Kojiki: The First Kami", blurb: "The Kojiki opens with a list of names. The first three kami appear alone, without partners, without parents, without explanation — and then hide themselves. What do they represent?", titleJa: 'トリスケリオン・古事記を読む：最初の神', blurbJa: '古事記は名前の一覧で始まる。最初の三柱の神は、伴侶も親も説明もなく現れ——そして姿を隠す。彼らは何を表しているのか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-01-the-first-kami', image: '/images/articles/triskelion-01-the-first-kami.png' },
  { num: 'T-01b', title: "Reading the Kojiki: The Ownerless God", blurb: "Amenominakanushi — the Lord of the August Centre of Heaven — has no cult, no shrine, no myth. He appears first in the cosmos and immediately vanishes. His absence is the point.", titleJa: 'トリスケリオン・古事記を読む：所有者なき神', blurbJa: '天之御中主——天の中心の主——には、崇拝も、神社も、神話もない。宇宙で最初に現れ、すぐに姿を消す。その不在こそが要点だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-02-the-ownerless-god', image: '/images/articles/triskelion-02-the-ownerless-god.png' },
  { num: 'T-01c', title: "Reading the Kojiki: The Two Forces", blurb: "The second and third kami form the first polarity in the cosmos — Takamimusubi and Kamimusubi, the High Creator and the Divine Creator. What does their pairing reveal about how the Kojiki understands reality?", titleJa: 'トリスケリオン・古事記を読む：二つの力', blurbJa: '二番目と三番目の神が宇宙最初の極性を形成する——高御産巣日と神産巣日、高い創造者と神聖な創造者。その対が、古事記の現実理解について何を明かすか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-03-the-two-forces', image: '/images/articles/triskelion-03-the-two-forces.png' },
  { num: 'T-01d', title: "Reading the Kojiki: The Tao and the Kojiki", blurb: "The Tao Te Ching says the Tao produces one, one produces two, two produces three, and three produces ten thousand things. The Kojiki's cosmology follows a strikingly similar logic.", titleJa: 'トリスケリオン・古事記を読む：老子と古事記', blurbJa: '老子は言う——道は一を生み、一は二を生み、二は三を生み、三は万物を生むと。古事記の宇宙論は、驚くほど似た論理に従っている。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-04-the-tao-and-the-kojiki', image: '/images/articles/triskelion-04-the-tao-and-the-kojiki.png' },
  { num: 'T-01e', title: "Reading the Kojiki: The Reed Shoot", blurb: "The fourth kami has the longest name in the primordial sequence and the most specific image — a reed shoot pushing up through formless mud. Why this image, and what does it mean?", titleJa: 'トリスケリオン・古事記を読む：葦の芽', blurbJa: '四番目の神は、原初の系列で最も長い名前と最も具体的なイメージを持つ——形なき泥を突き破る葦の芽。なぜこのイメージなのか、そしてそれは何を意味するのか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-05-the-reed-shoot', image: '/images/articles/triskelion-05-the-reed-shoot.png' },
  { num: 'T-01f', title: "Reading the Kojiki: The Standing Heaven", blurb: "The fifth and final Kotoamatsukami is Amenotokotachi — the Eternal Standing Heaven. What does it mean for heaven to stand? And why does the Kojiki end its solitary kami here?", titleJa: 'トリスケリオン・古事記を読む：立つ天', blurbJa: '五番目にして最後の別天津神は天之常立——永遠に立つ天。天が立つとはどういう意味か。そして古事記はなぜここで孤独な神を終えるのか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-06-the-standing-heaven', image: '/images/articles/triskelion-06-the-standing-heaven.png' },
  { num: 'T-01g', title: "Reading the Kojiki: The Paired World", blurb: "After the five solitary Kotoamatsukami, something changes. The cosmos begins producing kami in pairs — male and female together. The shift from solitary to paired is the Kojiki's first great structural turn.", titleJa: 'トリスケリオン・古事記を読む：対になる世界', blurbJa: '五柱の孤独な別天津神の後、何かが変わる。宇宙は神々を対——男と女——として生み出し始める。孤独から対への転換が、古事記の最初の大きな構造的転回だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-07-the-paired-world', image: '/images/articles/triskelion-07-the-paired-world.jpeg' },
  { num: 'T-01h', title: "Reading the Kojiki: Mud and Sand", blurb: "The first paired generation is Uhijini and Suhijini — the Lord of Mud Earth and the Lady of Sand Earth. Two types of earth, two principles of matter, and the beginning of a world that can be touched.", titleJa: 'トリスケリオン・古事記を読む：泥と砂', blurbJa: '最初の対の世代は宇比地邇と須比智邇——泥土の主と砂土の主。二種類の土、物質の二つの原理、そして触れることのできる世界の始まり。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-08-mud-and-sand', image: '/images/articles/triskelion-08-mud-and-sand.png' },
  { num: 'T-01i', title: "Reading the Kojiki: The Stake in the Ground", blurb: "The third generation is Tsunuguhi and Ikuguhi — the Lord of the Pointed Stake and the Lady of the Living Stake. Stakes driven into the earth: the first act of human-like world-making in the Kojiki.", titleJa: 'トリスケリオン・古事記を読む：地に打ち込まれた杭', blurbJa: '第三世代は角杙と活杙——尖った杙の主と生きた杙の主。地に打ち込まれた杙——古事記における人間的な世界創造の最初の行為。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-09-the-stake-in-the-ground', image: '/images/articles/triskelion-09-the-stake-in-the-ground.png' },
  { num: 'T-01j', title: "Reading the Kojiki: The First Dwelling", blurb: "The fourth generation is Otonoji and Otonobe — the Lord of the Great Door's Way and the Lady of the Great Reed Mat. A door. A mat. The cosmos is beginning to feel like a place where someone might live.", titleJa: 'トリスケリオン・古事記を読む：最初の住まい', blurbJa: '第四世代は意富斗能地と大斗乃弁——大きな扉の道の主と大きな葦の筵の主。扉。筵。宇宙が誰かが住めるような場所に感じられ始めている。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-10-the-first-dwelling', image: '/images/articles/triskelion-10-the-first-dwelling.png' },
  { num: 'T-01k', title: "Reading the Kojiki: The Binding Princess", blurb: "The sixth generation is Omotaru and Kukurihime — the Perfectly Complete One and the Princess Who Binds. What does it mean to bind, and what is being bound?", titleJa: 'トリスケリオン・古事記を読む：結びの姫', blurbJa: '第六世代は於母陀流と阿夜訶志古泥——完全に完成した者と結ぶ姫。結ぶとはどういう意味か、そして何が結ばれるのか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-11-the-binding-princess', image: '/images/articles/triskelion-11-the-binding-princess.png' },
  { num: 'T-01l', title: "Reading the Kojiki: The Invitation", blurb: "The seventh and final divine generation is Izanagi and Izanami — the One Who Invites and the One Who Is Invited. Before anything is created, there is an invitation.", titleJa: 'トリスケリオン・古事記を読む：誘い', blurbJa: '第七にして最後の神代は伊邪那岐と伊邪那美——誘う者と誘われる者。何も創られる前に、誘いがある。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-12-the-invitation', image: '/images/articles/triskelion-12-the-invitation.png' },
  { num: 'T-01m', title: "Reading the Kojiki: The Courtship and the Correction", blurb: "Izanagi and Izanami walk around the heavenly pillar. Izanami speaks first — and the first child is malformed. The Kojiki encodes something precise about order, voice, and the conditions for creation.", titleJa: 'トリスケリオン・古事記を読む：求婚と修正', blurbJa: '伊邪那岐と伊邪那美は天の御柱の周りを歩く。伊邪那美が先に語りかけ——最初の子は不完全だった。古事記は秩序、声、創造の条件について精密な何かを記している。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-13-the-courtship-and-the-correction', image: '/images/articles/triskelion-13-the-courtship-and-the-correction.png' },
  { num: 'T-01n', title: "Reading the Kojiki: The Birth of the Islands", blurb: "Once the correct order is established the creation proceeds with remarkable fertility. Japan is not made — it is born. The difference matters.", titleJa: 'トリスケリオン・古事記を読む：島々の誕生', blurbJa: '正しい秩序が確立されると、創造は驚くべき豊かさで進む。日本は作られるのではなく——生まれる。その違いは重要だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-14-the-birth-of-the-islands', image: '/images/articles/triskelion-14-the-birth-of-the-islands.png' },
  { num: 'T-01o', title: "Reading the Kojiki: The Fire That Kills", blurb: "Izanami dies giving birth to the fire kami. The world-creating couple is broken apart by the very act of creation. The Kojiki's first death is not random — it is structurally necessary.", titleJa: 'トリスケリオン・古事記を読む：死をもたらす火', blurbJa: '伊邪那美は火の神を産んで死ぬ。世界を創る対は創造の行為そのものによって引き裂かれる。古事記の最初の死は偶然ではない——構造的に必然だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-15-the-fire-that-kills', image: '/images/articles/triskelion-15-the-fire-that-kills.png' },
  { num: 'T-01p', title: "Reading the Kojiki: The Descent", blurb: "Izanagi cannot accept Izanami's death. He follows her into Yomi — the land of the dead. What he finds there changes everything about how Japan understands death, pollution, and return.", titleJa: 'トリスケリオン・古事記を読む：降下', blurbJa: '伊邪那岐は伊邪那美の死を受け入れられない。黄泉の国——死者の国——へ彼女を追う。そこで見たものが、日本の死・穢れ・帰還の理解をすべて変える。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-16-the-descent', image: '/images/articles/triskelion-16-the-descent.png' },
  { num: 'T-01q', title: "Reading the Kojiki: The Negotiation at the Boulder", blurb: "Izanagi flees Yomi with the dead pursuing him. At the border between worlds he rolls a great boulder across the entrance. The exchange that follows is one of the most precise moments in the Kojiki.", titleJa: 'トリスケリオン・古事記を読む：岩のもとでの交渉', blurbJa: '伊邪那岐は死者に追われながら黄泉から逃げる。世界の境界で大岩を入口に転がす。その後に続く交換は古事記の最も精密な瞬間の一つだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-17-the-negotiation-at-the-boulder', image: '/images/articles/triskelion-17-the-negotiation-at-the-boulder.png' },
  { num: 'T-01r', title: "Reading the Kojiki: The Purification", blurb: "Izanagi emerges from Yomi and goes immediately to water. The purification that follows produces some of the most important kami in the Japanese pantheon — including Amaterasu herself.", titleJa: 'トリスケリオン・古事記を読む：禊', blurbJa: '伊邪那岐は黄泉から現れ、すぐに水へ向かう。続く禊は日本の神々の中で最も重要な神々を生み出す——天照大御神を含めて。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-18-the-purification', image: '/images/articles/triskelion-18-the-purification.png' },
  { num: 'T-01s', title: "Reading the Kojiki: What the Myth Might Remember", blurb: "Every mythology encodes history. The Izanagi and Izanami cycle has a second reading — one that sits alongside the cosmological reading and asks what actual human events this myth might be preserving.", titleJa: 'トリスケリオン・古事記を読む：神話が記憶しているかもしれないもの', blurbJa: 'あらゆる神話は歴史を符号化している。伊邪那岐と伊邪那美の循環には第二の読み方がある——宇宙論的読み方と並置され、この神話が実際にどんな人間の出来事を保存しているかを問う読み方だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-19-what-the-myth-might-remember', image: '/images/articles/triskelion-19-what-the-myth-might-remember.png' },
  { num: 'T-01t', title: "Reading the Kojiki: The Boulder and the Peace", blurb: "Before the story continues, one detail of the Yomi sequence deserves its own consideration — the boulder at the boundary, and what it means that the separation was negotiated rather than forced.", titleJa: 'トリスケリオン・古事記を読む：岩と和平', blurbJa: '物語が続く前に、黄泉の系列の一つの細部が独自の考察に値する——境界の岩、そして分離が強制ではなく交渉されたことが何を意味するか。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-20-the-boulder-and-the-peace', image: '/images/articles/triskelion-20-the-boulder-and-the-peace.png' },
  { num: 'T-01u', title: "Reading the Kojiki: The Three Noble Children", blurb: "Three kami born from a single act of washing — Amaterasu, Tsukuyomi, Susanoo — and the three domains of the cosmos assigned in a moment.", titleJa: 'トリスケリオン・古事記を読む：三貴子', blurbJa: '一つの禊から生まれた三柱の神々——天照、月読、須佐之男——そして瞬く間に分かたれた三つの宇宙の領域。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-21-the-three-noble-children', image: '/images/articles/triskelion-21-the-three-noble-children.jpeg' },
  { num: 'T-01v', title: "Reading the Kojiki: The Cave", blurb: "Amaterasu withdraws into the Rock Cave of Heaven. The world goes dark. What draws her out is not force — it is a mirror, laughter, and the reflection of her own light.", titleJa: 'トリスケリオン・古事記を読む：岩戸', blurbJa: '天照は天岩戸に引きこもる。世界は暗くなる。彼女を引き出すのは力ではなく——鏡と笑い、そして自らの光の反射だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-22-the-cave', image: '/images/articles/triskelion-22-the-cave.png' },
  { num: 'T-01w', title: "Reading the Kojiki: The Exile and What Was Built", blurb: "Expelled from heaven, Susanoo descends to Izumo — not the sea he was assigned, but a river mouth facing the Korean peninsula. What he builds there changes everything.", titleJa: 'トリスケリオン・古事記を読む：追放と築かれたもの', blurbJa: '天から追放された須佐之男は出雲へ降りる——与えられた海ではなく、朝鮮半島を向く川口へ。そこで築かれたものが、すべてを変えた。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-23-the-exile-and-what-was-built', image: '/images/articles/triskelion-23-the-exile-and-what-was-built.png' },
  { num: 'T-01x', title: "Reading the Kojiki: The Settlement", blurb: "Okuninushi yields the visible world. In exchange: a great shrine and governance of the hidden realm. The most honest political statement in the entire Kojiki.", titleJa: 'トリスケリオン・古事記を読む：国譲り', blurbJa: '大国主は顕世を譲る。その代わりに大社の建立と幽世の支配権を得る。古事記における最も誠実な政治的声明。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-24-the-settlement', image: '/images/articles/triskelion-24-the-settlement.png' },
  // TRISKELION — Book II: The Framework
  { num: 'T-02', title: 'The Framework: From Two to Three', blurb: 'Binary thinking is the oldest cognitive tool we have — fast, decisive, and systematically incomplete. The step from two to three does not merely add one more option. It generates an entirely new kind of reality.', titleJa: 'トリスケリオン・枠組み：二から三へ', blurbJa: '二項対立的思考は人類が持つ最も古い認知ツールだ——速く、決定的で、体系的に不完全。二から三へのステップは、単に選択肢を一つ増やすのではない。まったく新しい種類の現実を生み出す。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-01-from-two-to-three', image: '/images/articles/triskelion-b2-01-from-two-to-three.png' },
  { num: 'T-02b', title: 'The Framework: Three Ways of Being in the World', blurb: 'Every landscape contains a mountain, a river, and a sea. These three geographic relationships produce three fundamentally different ways of organising human life — and the same structure recurs at every scale.', titleJa: 'トリスケリオン・枠組み：世界における三つの在り方', blurbJa: 'あらゆる景観に、山と川と海がある。この三つの地理的関係が、人間の生活を組織する根本的に異なる三つの様式を生み出す——同じ構造があらゆるスケールで繰り返される。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-02-three-ways-of-being-in-the-world', image: '/images/articles/triskelion-b2-02-three-ways-of-being-in-the-world.png' },
  { num: 'T-02c', title: 'The Framework: The Same Discovery', blurb: 'The mitsudomoe in Japan. The triskelion in Celtic Europe. The Christian Trinity. Three completely independent traditions, separated by millennia and oceans, encoding the same rotating-three structure. This is not coincidence.', titleJa: 'トリスケリオン・枠組み：同じ発見', blurbJa: '日本の三つ巴。ケルトのトリスケリオン。キリスト教の三位一体。千年と大洋に隔てられた三つの完全に独立した伝統が、同じ回転する三つの構造を記号化している。これは偶然ではない。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-03-the-same-discovery', image: '/images/articles/triskelion-b2-03-the-same-discovery.png' },
  { num: 'T-02d', title: 'The Framework: The Mountain People', blurb: 'The Mountain People\'s world begins with a specific relationship with a specific place — this mountain, this forest, this river. Their greatest strength and their greatest vulnerability are the same thing.', titleJa: 'トリスケリオン・枠組み：山の民', blurbJa: '山の民の世界は、特定の場所との特定の関係から始まる——この山、この森、この川。彼らの最大の強みと最大の脆弱性は同じものだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-04-the-mountain-people', image: '/images/articles/triskelion-b2-04-the-mountain-people.png' },
  { num: 'T-02e', title: 'The Framework: The River People', blurb: 'The River People\'s world begins with water that can be controlled. Wherever flat fertile land can be watered systematically, their civilisation follows — not because people choose hierarchy, but because the agricultural system requires it.', titleJa: 'トリスケリオン・枠組み：川の民', blurbJa: '川の民の世界は、制御できる水から始まる。平坦で肥沃な大地を組織的に灌漑できるところならどこでも、彼らの文明が生まれる——人々が階層を選ぶからではなく、農業システムがそれを必要とするからだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-05-the-river-people', image: '/images/articles/triskelion-b2-05-the-river-people.png' },
  { num: 'T-02f', title: 'The Framework: The Sea People', blurb: 'You are in a foreign harbour. The person across the table speaks a different language and prays to different gods. You have goods they want. They have goods you want. How do you trade? The Sea People solved this — and their solution transformed civilisation.', titleJa: 'トリスケリオン・枠組み：海の民', blurbJa: 'あなたは異国の港にいる。テーブルの向こうの人物は異なる言語を話し、異なる神に祈る。あなたには相手が欲しい物がある。どうやって取引するか。海の民はこれを解決した——その解決策が文明を変えた。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-06-the-sea-people', image: '/images/articles/triskelion-b2-06-the-sea-people.png' },
  { num: 'T-02g', title: 'The Framework: How Trust Works', blurb: 'The three poles produce three completely different answers to how you get people to cooperate — personal trust, institutional trust, and impersonal mechanisms. These answers are partially incompatible, and that incompatibility generates much of the political conflict in any civilisation that contains all three.', titleJa: 'トリスケリオン・枠組み：信頼の仕組み', blurbJa: '三極は、人々をどのように協力させるかについて三つの完全に異なる答えを生み出す——個人的信頼、制度的信頼、非人格的メカニズム。これらの答えは部分的に相容れず、その非互換性があらゆる文明の政治的対立の多くを生む。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-07-how-trust-works', image: '/images/articles/triskelion-b2-07-how-trust-works.png' },
  { num: 'T-02h', title: 'The Framework: The Three Microcosms', blurb: 'The three-pole framework operates at every scale simultaneously — from a single valley to the entire planet. Japan offers one of the clearest cases: northern Kyushu as Sea pole, Izumo as Mountain pole, the Yamato plain as River pole.', titleJa: 'トリスケリオン・枠組み：三つのミクロコスモス', blurbJa: '三極フレームワークはあらゆるスケールで同時に機能する——一つの谷から地球全体まで。日本はその最も明確なケースを提供する：北部九州が海の極、出雲が山の極、大和平野が川の極。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-08-the-three-microcosms', image: '/images/articles/triskelion-b2-08-the-three-microcosms.png' },
  { num: 'T-02i', title: 'The Framework: The Three Sacred Objects', blurb: 'The magatama, the mirror, and the sword — held in three separate locations, never displayed. One reading: three objects representing the three civilisational traditions whose synthesis the imperial institution claims to embody.', titleJa: 'トリスケリオン・枠組み：三つの神器', blurbJa: '勾玉、鏡、剣——三か所に別々に保管され、決して展示されない。一つの読み：皇室制度が体現を主張する三つの文明的伝統を代表する三つの物。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-09-the-three-sacred-objects', image: '/images/articles/triskelion-b2-09-the-three-sacred-objects.png' },
  { num: 'T-02j', title: 'The Framework: The Mitsudomoe', blurb: 'Three comma-shapes rotating around a centre. It appears in Japan in the Nara period — the same decades that produced the Kojiki. The Celtic triskelion arrived at the same symbol independently, at the opposite end of the Eurasian landmass. The mitsudomoe is not a declaration. It is a permanent question.', titleJa: 'トリスケリオン・枠組み：三つ巴', blurbJa: '中心の周りを回転する三つの勾玉形。古事記を生んだのと同じ奈良時代に日本に現れる。ケルトのトリスケリオンはユーラシア大陸の反対端で独立して同じシンボルに到達した。三つ巴は宣言ではない。永続的な問いだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-10-the-mitsudomoe', image: '/images/articles/triskelion-b2-10-the-mitsudomoe.png' },
  { num: 'T-02k', title: 'The Framework: The Goddess in Heaven', blurb: 'When hierarchy suppresses female shamanic authority, the need for the feminine sacred does not disappear. Instead, the hierarchy promotes. The real shamanic women are demoted. The celestial goddess is elevated. The suppression and the worship are two sides of the same operation.', titleJa: 'トリスケリオン・枠組み：天の女神', blurbJa: '階層が女性のシャーマン的権威を抑圧するとき、女性的な聖なるものへの需要は消えない。代わりに、階層は昇格させる。現実のシャーマンの女性たちは降格される。天の女神は高められる。抑圧と崇拝は同じ操作の二つの側面だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-11-the-goddess-in-heaven', image: '/images/articles/triskelion-b2-11-the-goddess-in-heaven.png' },
  { num: 'T-02l', title: 'The Framework: The Balance', blurb: 'If the three-pole framework is correct, civilisations closer to balance should produce better outcomes. The evidence suggests they do. Scandinavia consistently tops global quality-of-life measurements — and the three-pole analysis of why is specific.', titleJa: 'トリスケリオン・枠組み：均衡', blurbJa: '三極フレームワークが正しければ、均衡に近い文明はより良い結果を生むはずだ。証拠はそれを示唆する。スカンジナビアは世界の生活の質の測定で一貫して首位に立つ——その理由についての三極分析は具体的だ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-12-the-balance', image: '/images/articles/triskelion-b2-12-the-balance.png' },
  { num: 'T-02m', title: 'The Framework: The World Today', blurb: 'The three-pole framework is not just a historical tool — it is a diagnostic. The Sea People coalition is globally dominant. The River People coalition is resurgent. The Mountain People are in crisis. What each needs from the others is the same question the Kojiki was trying to answer.', titleJa: 'トリスケリオン・枠組み：今日の世界', blurbJa: '三極フレームワークは単なる歴史的ツールではない——診断だ。海の民の連合が世界的に支配的だ。川の民の連合が復興しつつある。山の民は危機の中にある。それぞれが他者から何を必要とするか——古事記が答えようとしていたのと同じ問いだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b2-13-the-world-today', image: '/images/articles/triskelion-b2-13-the-world-today.png' },
  // TRISKELION — Book III: Japan
  { num: 'T-03', title: 'Japan: Before the Synthesis', blurb: 'For fourteen thousand years before the continental arrivals, the Jomon people inhabited the Japanese archipelago. The three poles did not arrive as a package — they arrived sequentially, met unevenly, and negotiated their relationship across centuries.', titleJa: 'トリスケリオン・日本：統合以前', blurbJa: '大陸からの渡来人が到来する以前の一万四千年間、縄文人が日本列島に暮らしていた。三極はひとまとめに到来したのではない——順次到来し、不均等に出会い、数世紀にわたって互いの関係を交渉した。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-01-before-the-synthesis', image: '/images/articles/triskelion-b3-01-before-the-synthesis.png' },
  { num: 'T-03b', title: 'Japan: Himiko and the Sea People\'s Sacred Queen', blurb: 'In 238 CE a Japanese ruler sent an envoy to the Chinese court. The records describe Himiko — a shamanic queen in sacred seclusion, served by a thousand women and a single male relative. Whether she is the historical memory behind Amaterasu remains one of the most compelling questions in Japanese mythology.', titleJa: 'トリスケリオン・日本：卑弥呼と海の民の聖なる女王', blurbJa: '238年、日本の支配者が中国朝廷に使者を送った。記録は卑弥呼を描写する——千人の女性と一人の男性の親族に仕えられながら聖なる隠遁に生きるシャーマンの女王。彼女がアマテラスの背後にある歴史的記憶かどうかは、日本神話で最も説得力ある問いの一つだ。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-02-himiko-and-the-sea-peoples-sacred-queen', image: '/images/articles/triskelion-b3-02-himiko-and-the-sea-peoples-sacred-queen.png' },
  { num: 'T-03c', title: 'Japan: The Izumo Coalition', blurb: 'A sea-arriving figure integrates into a Mountain People community, defeats an oppressive local power through continental knowledge, and builds something new from the combination. Whether or not it preserves historical memory, the Susanoo mythology encodes a specific pattern — not conquest but coalition.', titleJa: 'トリスケリオン・日本：出雲連合', blurbJa: '海から到来した存在が山の民のコミュニティに統合し、大陸的知識で抑圧的な地域の権力を倒し、その組み合わせから新しい何かを構築する。歴史的記憶を保存しているかどうかにかかわらず、スサノオの神話は特定のパターンを記号化している——征服ではなく連合として。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-03-the-izumo-coalition', image: '/images/articles/triskelion-b3-03-the-izumo-coalition.png' },
  { num: 'T-03d', title: 'Japan: The Yamato Synthesis', blurb: 'The Kojiki says to all three traditions simultaneously: you are real, you are honored, you belong here — and none of you is the whole story. A founding text that chose incorporation over erasure, and preserved the Izumo tradition on terms that maintained its essential character.', titleJa: 'トリスケリオン・日本：ヤマトの統合', blurbJa: '古事記は三つすべての伝統に同時にこう言う：あなたは本物だ、あなたは尊重される、あなたはここに属する——そして誰もが物語の全体ではない。消去ではなく取り込みを選んだ創設テキスト。出雲の伝統をその本質的な性格を保つ条件で保存した。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-04-the-yamato-synthesis', image: '/images/articles/triskelion-b3-04-the-yamato-synthesis.png' },
  { num: 'T-03e', title: 'Japan: The Hime-Hiko System', blurb: 'The Wei Zhi\'s Himiko embodies a dual-authority structure in which a sacred female figure and a male administrative figure govern together — each holding a domain the other cannot. This hime-hiko system is encoded in the Kojiki\'s cosmology and still survives, reduced, in the miko tradition.', titleJa: 'トリスケリオン・日本：ヒメヒコ制', blurbJa: '魏志倭人伝の卑弥呼は、聖なる女性と男性の行政的人物が共に統治する二重権威の構造を体現している——それぞれが他方には持てない領域を保持して。このヒメヒコ制は古事記の宇宙論に記号化され、縮小された形で今も巫女の伝統に生き残っている。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-05-the-hime-hiko-system', image: '/images/articles/triskelion-b3-05-the-hime-hiko-system.png' },
  { num: 'T-03f', title: 'Japan: The Heian Flowering', blurb: 'The Heian period is the closest Japan came to allowing the Mountain People\'s aesthetic sensibility to shape the dominant culture. Murasaki Shikibu. Sei Shonagon. Mono no aware. The cherry blossom sacred because it is exactly what it is in this moment, falling. It could not last — but it gave Japan its most distinctive cultural gifts.', titleJa: 'トリスケリオン・日本：平安の花開き', blurbJa: '平安時代は、日本が山の民の美的感性を支配的な文化を形作ることを許した最も近い時代だ。紫式部。清少納言。もののあわれ。桜の花がこの瞬間に散りながらまさにそれであるから神聖だ。続かなかった——だが日本に最も独特な文化的贈り物を与えた。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-06-the-heian-flowering', image: '/images/articles/triskelion-b3-06-the-heian-flowering.png' },
  { num: 'T-03g', title: 'Japan: The Institutionalized Tension', blurb: 'The Tokugawa shogunate formalized the three-pole tension into a stable social hierarchy. Samurai at the top, merchants at the bottom — the River People\'s ideology stated plainly. And yet the officially lowest class produced kabuki, ukiyo-e, haiku, and Basho. The frog. The old pond. The sound of water.', titleJa: 'トリスケリオン・日本：制度化された緊張', blurbJa: '徳川幕府は三極の緊張を安定した社会的階層へと公式化した。頂点の武士、底辺の商人——川の民のイデオロギーを率直に述べたもの。それでも公式に最も低い階級が歌舞伎、浮世絵、俳句、そして芭蕉を生み出した。蛙。古池。水の音。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-07-the-institutionalized-tension', image: '/images/articles/triskelion-b3-07-the-institutionalized-tension.png' },
  { num: 'T-03h', title: 'Japan: The Meiji Gamble', blurb: 'The Meiji leaders read the Western dual structure correctly — liberal institutions at home, hierarchical power abroad — and chose to replicate it. The plan was conceptually coherent. It failed because the Phase 1 apparatus developed its own logic, and Phase 3 was built on the ruins of the traditions that should have carried it.', titleJa: 'トリスケリオン・日本：明治の賭け', blurbJa: '明治のリーダーたちは西洋の二重構造を正しく読んだ——国内の自由主義的制度と海外の階層的権力——そしてそれを模倣することを選んだ。計画は概念的に首尾一貫していた。第一段階の装置が独自の論理を発展させ、第三段階がそれを担うべき伝統の廃墟の上に構築されたために失敗した。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-08-the-meiji-gamble', image: '/images/articles/triskelion-b3-08-the-meiji-gamble.png' },
  { num: 'T-03i', title: 'Japan: The Unresolved Present', blurb: 'Japan has been living with the three-pole tension for fifteen hundred years. The corporate hierarchy redirected from the military hierarchy. The tatemae/honne split as the institutionalized gap between public performance and private truth. The kami still in the mountains. The synthesis always incomplete. The question still open.', titleJa: 'トリスケリオン・日本：未解決の現在', blurbJa: '日本は三極の緊張とともに千五百年間生きてきた。軍事的階層から転換した企業階層。建前・本音の分裂として制度化された公的パフォーマンスと私的真実の隔たり。神々はまだ山にいる。統合は常に不完全だ。問いは今も開かれている。', category: 'triskelion', categoryLabel: 'Triskelion', categoryLabelJa: 'トリスケリオン', slug: 'triskelion-b3-09-the-unresolved-present', image: '/images/articles/triskelion-b3-09-the-unresolved-present.png' },
]
export const categories = [
  { key: 'all', label: 'All', labelJa: 'すべて' },
  { key: 'culture', label: 'Culture & Society', labelJa: '文化・社会' },
  { key: 'spirituality', label: 'Spirituality', labelJa: '精神・宗教' },
  { key: 'theory', label: 'Original Theory', labelJa: '独自理論' },
  { key: 'history', label: 'History & Myth', labelJa: '歴史・神話' },
  { key: 'science', label: 'Science & Mind', labelJa: '科学・思想' },
  { key: 'japan', label: 'Japan & Culture', labelJa: '日本・文化' },
  { key: 'triskelion', label: 'Triskelion', labelJa: 'トリスケリオン' },
]

export const categoryGroups = [
  { key: 'culture', label: 'Culture & Society', labelJa: '文化・社会' },
  { key: 'spirituality', label: 'Spirituality & Religion', labelJa: '精神・宗教' },
  { key: 'theory', label: 'Original Theories', labelJa: '独自理論' },
  { key: 'history', label: 'History & Mythology', labelJa: '歴史・神話' },
  { key: 'science', label: 'Science & Mind', labelJa: '科学・思想' },
  { key: 'japan', label: 'Japan & Culture', labelJa: '日本・文化' },
]

// Public-facing articles — human written only
export const humanArticles = articles.filter(a => a.authored === 'human')