export type Article = {
  num: string
  title: string
  blurb: string
  titleJa: string
  blurbJa: string
  category: 'culture' | 'spirituality' | 'theory' | 'history' | 'science' | 'japan'
  categoryLabel: string
  categoryLabelJa: string
  slug: string
  image?: string
}

export const articles: Article[] = [
  // CULTURE & SOCIETY
  { num: '01', title: 'The Geography of Power: Floodplain vs Fractured-Sea Cultures', blurb: 'Why whole civilisations think differently — and why the answer lies in the shape of the land. The first article in the Geography of Power series.', titleJa: '権力の地理学：氾濫原文明と分裂海文明', blurbJa: '文明全体がなぜ異なる思考をするのか——その答えは土地の形にある。権力の地理学シリーズの第一回。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'floodplain-vs-fractured-sea', image: '/images/articles/floodplain-vs-fractured-sea.png' },
  { num: '01b', title: 'The Geography of Power: The Geography of Hierarchy', blurb: 'Fragmented geography produces competition. But the same competitive pressure also produces something else — hereditary hierarchy built around bloodlines, land, and family groups.', titleJa: '権力の地理学：階層の地理', blurbJa: '分断された地形は競争を生む。しかし同じ競争圧力は別のものも生み出す——血統、土地、家族集団を中心とした世襲的階層だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'geography-of-hierarchy', image: '/images/articles/geography-of-hierarchy.png' },
  { num: '01c', title: 'The Geography of Power: Two Shapes of Hierarchy', blurb: 'In Japan, hierarchy describes a relationship in a context. In Victorian England, it described a person. The difference — relational vs ontological — has consequences that still echo today.', titleJa: '権力の地理学：二つの階層の形', blurbJa: '日本では、階層は文脈の中の関係を表す。ビクトリア朝イギリスでは、人そのものを表した。関係的対存在論的——その違いは今日も響き続けている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'two-shapes-of-hierarchy', image: '/images/articles/two-shapes-of-hierarchy.png' },
  { num: '02', title: 'Why Dating Apps Structurally Fail Men — And How to Fix Them', blurb: 'The architecture of modern dating apps creates a structural mismatch that no better photo can fix.', titleJa: 'マッチングアプリが男性に不利な構造的理由', blurbJa: '現代のマッチングアプリの設計には、写真を改善しても解決できない構造的ミスマッチがある。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'dating-apps-fail-men', image: '/images/articles/dating-apps-fail-men.jpeg' },
  { num: '03', title: 'Debate Cultures vs Scolding Cultures', blurb: 'Two fundamentally different ways of handling disagreement — and what they reveal about a society.', titleJa: '議論文化と叱責文化', blurbJa: '意見の相違への二つの根本的アプローチ——それは社会の本質を映し出す。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'debate-vs-scolding-cultures', image: '/images/articles/debate-vs-scolding-cultures.png' },
  { num: '04', title: 'Nordic Social Scripts: What Scandinavia Gets Right About Social Pressure', blurb: 'The hidden rules governing Scandinavian social life — and why they might be the most sophisticated system in the world.', titleJa: '北欧の社会スクリプト：スカンジナビアが社会的圧力について正しいこと', blurbJa: '北欧の社会生活を支配する隠れたルール——それは世界で最も洗練されたシステムかもしれない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'nordic-social-scripts', image: '/images/articles/nordic-social-scripts.jpeg' },
  { num: '05', title: 'Was Edo Japan Happier Than Modern Japan?', blurb: 'A pre-industrial society with no growth economy, near-zero crime, and high life satisfaction. What can it teach us?', titleJa: '江戸時代の日本は現代より幸福だったのか', blurbJa: '経済成長なし、ほぼゼロの犯罪率、高い生活満足度——前工業化社会から何を学べるか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'edo-japan-happiness', image: '/images/articles/edo-japan-happiness.png' },
  { num: '06', title: 'How Cultures Misread Each Other in Australia', blurb: 'Australia as a collision point for incompatible social software — and what happens when nobody notices.', titleJa: 'オーストラリアにおける文化の誤読', blurbJa: '相容れない社会的ソフトウェアの衝突点としてのオーストラリア——誰も気づかないと何が起きるか。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'cultures-misread-australia', image: '/images/articles/cultures-misread-australia.jpeg' },
  { num: '07', title: 'East vs West: Different Kinds of Tough', blurb: "Resilience looks different depending on where you were forged. Neither is stronger — they're built for different storms.", titleJa: '東洋と西洋：異なる強さの形', blurbJa: 'どこで鍛えられたかによって、強さの姿は異なる。どちらが優れているわけではなく、異なる嵐のために作られている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'east-vs-west-tough', image: '/images/articles/east-vs-west-tough.png' },
  { num: '08', title: 'Relational Morality vs Principled Morality: Two Ways of Being Good', blurb: 'Is morality about universal rules or about the people in front of you? The answer divides civilisations.', titleJa: '関係的道徳と原則的道徳：二つの善のあり方', blurbJa: '道徳とは普遍的ルールのことか、それとも目の前の人々についてのものか——この答えが文明を分ける。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'relational-vs-principled-morality', image: '/images/articles/relational-vs-principled-morality.png' },

  // SPIRITUALITY & RELIGION
  { num: '09', title: 'Gnosticism and the Demiurge: The Hidden Creation Story', blurb: "What if the God who made the world isn't the highest God? The ancient heresy that still makes uncomfortable sense.", titleJa: 'グノーシス主義とデミウルゴス：隠された創造の物語', blurbJa: '世界を作った神が最高の神でないとしたら？今もなお不穏な意味を持つ古代の異端思想。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'gnosticism-and-the-demiurge', image: '/images/articles/gnosticism-and-the-demiurge.jpeg' },
  { num: '10', title: 'The Gospel of Judas: Was He the Real Hero?', blurb: 'The suppressed gospel that rewrites the most famous betrayal in history.', titleJa: 'ユダの福音書：彼は本当の英雄だったのか', blurbJa: '歴史上最も有名な裏切りを書き換える、抑圧された福音書。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'gospel-of-judas', image: '/images/articles/gospel-of-judas.jpeg' },
  { num: '11', title: 'The Book of Enoch: What the Bible Left Out', blurb: 'Angels who fell for human women, giants who walked the earth, and a cosmology the early church buried.', titleJa: 'エノク書：聖書が省いたもの', blurbJa: '人間の女性に恋した天使、地を歩いた巨人、そして初期教会が埋葬した宇宙論。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'book-of-enoch', image: '/images/articles/book-of-enoch.jpeg' },
  { num: '12', title: 'Is Christianity True? The Historical Case', blurb: 'A fair, serious look at the historical evidence for Christianity — without assuming the answer in advance.', titleJa: 'キリスト教は真実か？歴史的証拠', blurbJa: '答えを先に決めずに、キリスト教の歴史的証拠を公平かつ真剣に検討する。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'is-christianity-true', image: '/images/articles/is-christianity-true.jpeg' },
  { num: '12b', title: 'Is Christianity True? The Philosophical Case', blurb: 'The historical evidence is compelling but not conclusive. This article argues that the ambiguity might be the point — and makes the case for why calibrated evidence is what we should expect.', titleJa: 'キリスト教は真実か？哲学的論証', blurbJa: '歴史的証拠は説得力があるが決定的ではない。この記事は、その曖昧さこそが要点かもしれないと論じ、調整された証拠がなぜ私たちが期待すべきものかを論じる。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'is-christianity-true-2', image: '/images/articles/is-christianity-true-2.png' },
  { num: '13', title: 'Sophia: The Forgotten Feminine Divine', blurb: 'The goddess hidden inside Western monotheism — erased, suppressed, and still there if you know where to look.', titleJa: 'ソフィア：忘れられた女性神', blurbJa: '西洋一神教の内側に隠れた女神——消去され、抑圧され、それでもまだそこにいる。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'sophia-feminine-divine', image: '/images/articles/sophia-feminine-divine.jpeg' },
  { num: '14', title: 'Kensho vs Satori: Two Kinds of Awakening, Two Kinds of History', blurb: 'Zen distinguishes between a glimpse and full realisation. The difference maps onto how entire cultures understand transformation.', titleJa: '見性と悟り：二種類の覚醒、二種類の歴史', blurbJa: '禅は一瞥と完全な悟りを区別する。その違いは、文化全体が変容をどう理解するかに対応する。', category: 'spirituality', categoryLabel: 'Spirituality & Religion', categoryLabelJa: '精神・宗教', slug: 'kensho-vs-satori', image: '/images/articles/kensho-vs-satori.jpeg' },

  // ORIGINAL THEORIES
  { num: '15', title: 'Yin-Yang as a Fractal Map of the World', blurb: "The ancient symbol isn't just about balance. It's a recursive model of how everything contains its opposite.", titleJa: '陰陽：世界のフラクタル地図として', blurbJa: 'あの古代の象徴は単なるバランスではない。あらゆるものが対立を内包するという再帰的モデルだ。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'yin-yang-fractal-map', image: '/images/articles/yin-yang-fractal-map.png' },
  { num: '16', title: 'Fusion: A Theory of How Civilisations Evolve', blurb: 'An original framework for understanding how cultures absorb, resist, and transform under contact with each other.', titleJa: '融合論：文明の進化についての理論', blurbJa: '文化が互いに接触する中でいかに吸収し、抵抗し、変容するかを理解するための独自フレームワーク。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'fusion-theory', image: '/images/articles/fusion-theory.jpeg' },
  { num: '17', title: 'Uncertainty as Power: Why Not Knowing Is a Strategic Strength', blurb: 'The world rewards those who pretend to certainty. But the deepest strategic advantage may lie in the opposite direction.', titleJa: '不確実性という力：知らないことが戦略的強みになる理由', blurbJa: '世界は確実性を装う人を報いる。しかし最も深い戦略的優位は逆方向にあるかもしれない。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'uncertainty-as-power', image: '/images/articles/uncertainty-as-power.jpeg' },
  { num: '18', title: "Humanity as the Galaxy's Ungovernable Wild Card", blurb: "Why Earth's chaos, contradiction, and refusal to optimise might be our most important trait in a cosmic context.", titleJa: '銀河の制御不能なワイルドカードとしての人類', blurbJa: '地球の混沌、矛盾、そして最適化への拒否が、宇宙的文脈で最も重要な特質かもしれない理由。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'humanity-wild-card', image: '/images/articles/humanity-wild-card.jpeg' },
  { num: '19', title: 'How the Sage Digests the World: A Model of Meaning-Making', blurb: 'A framework for how wisdom traditions absorb experience — and why most people skip the most important step.', titleJa: '賢者はいかに世界を消化するか：意味形成のモデル', blurbJa: '知恵の伝統が経験をいかに吸収するか——そしてなぜほとんどの人が最も重要なステップを飛ばすのか。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'sage-digests-the-world', image: '/images/articles/sage-digests-the-world.jpeg' },

  // HISTORY & MYTHOLOGY
  { num: '20', title: 'Queen Himiko and the Mystery of Yamatai', blurb: "Japan's first ruler was a shaman queen who vanished from the historical record. What really happened?", titleJa: '卑弥呼と邪馬台国の謎', blurbJa: '日本最初の支配者はシャーマン女王だったが、歴史の記録から消えた。本当に何が起きたのか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'queen-himiko-yamatai', image: '/images/articles/queen-himiko-yamatai.jpeg' },
  { num: '21', title: "Amaterasu and Susanoo: Japan's Creation Myths Decoded", blurb: "The sun goddess and the storm god aren't just myths — they encode Japan's deepest tensions about order and chaos.", titleJa: '天照大神とスサノオ：日本の創造神話の解読', blurbJa: '太陽の女神と嵐の神は単なる神話ではない——秩序と混沌についての日本の最も深い緊張を符号化している。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'amaterasu-and-susanoo', image: '/images/articles/amaterasu-and-susanoo.jpeg' },
  { num: '22', title: 'Did a Chinese Immortality-Seeker Found Japan?', blurb: 'The strange legend of Xu Fu — the man who sailed east looking for eternal life and may never have returned.', titleJa: '中国の不死探求者が日本を建国したのか', blurbJa: '東へ向けて永遠の命を求めて航海し、二度と戻らなかったかもしれない男——徐福の奇妙な伝説。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'xu-fu-founded-japan', image: '/images/articles/xu-fu-founded-japan.jpeg' },
  { num: '23', title: 'Fukuzawa Yukichi: The Man on the Banknote', blurb: "Japan's most celebrated Meiji intellectual introduced Western liberty and independence to a modernising nation. His face is on the currency. His argument was buried.", titleJa: '福澤諭吉：紙幣の男', blurbJa: '日本でもっとも称えられた明治の知識人は、近代化する国家に西洋の自由と独立を紹介した。顔は紙幣にある。論拠は埋葬された。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-1-who-he-was', image: '/images/articles/fukuzawa-yukichi.png' },
  { num: '23b', title: 'Fukuzawa Yukichi: The Warning', blurb: "His famous essay on leaving Asia is what Japan remembered. The deeper argument — that obedient minds cannot sustain a free nation — is what Japan forgot.", titleJa: '福澤諭吉：警告', blurbJa: '脱亜論は日本が記憶したものだ。より深い論拠——服従する精神は自由な国家を維持できない——が日本が忘れたものだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-2-the-warning', image: '/images/articles/fukuzawa-2-the-warning.jpeg' },
  { num: '23c', title: 'Fukuzawa Yukichi: Tokugawa Psychology', blurb: "Tokugawa Japan had a tradition of remonstrance — loyal retainers could tell their lords they were wrong. Fukuzawa saw exactly why that wasn't enough.", titleJa: '福澤諭吉：徳川の心理', blurbJa: '徳川日本には諫言の伝統があった。忠実な家臣は主君に誤りを伝えられた。福澤はなぜそれで不十分かを正確に見抜いた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-3-tokugawa-psychology', image: '/images/articles/fukuzawa-3-tokugawa-psychology.jpeg' },
  { num: '23d', title: 'Fukuzawa Yukichi: He Saw It Happening', blurb: "Fukuzawa lived until 1901 — long enough to watch the Meiji project be captured by exactly the compliance architecture he had warned against.", titleJa: '福澤諭吉：それが起きるのを見た', blurbJa: '福澤は1901年まで生きた。明治プロジェクトが彼が警告した服従のアーキテクチャに乗っ取られるのを見るのに十分な時間だった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-4-he-saw-it-happening', image: '/images/articles/fukuzawa-4-he-saw-it-happening.jpeg' },
  { num: '23e', title: 'Fukuzawa Yukichi: How Japan Buried Him', blurb: "Japan honoured Fukuzawa grandly — his face on the banknote, his name on the university. The mechanism for honouring him was also the mechanism for neutralising him.", titleJa: '福澤諭吉：日本はいかに彼を埋葬したか', blurbJa: '日本は福澤を壮大に称えた——顔は紙幣に、名前は大学に。彼を称えるメカニズムはまた、彼を無力化するメカニズムでもあった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'fukuzawa-5-memorialisation', image: '/images/articles/fukuzawa-5-memorialisation.png' },

  // SCIENCE & MIND
  { num: '24', title: 'Yamanaka Factors: Can We Reverse Ageing?', blurb: 'The Nobel Prize-winning discovery that cells can be reprogrammed — and what it might mean for the human lifespan.', titleJa: '山中因子：老化を逆転できるか', blurbJa: 'ノーベル賞受賞の発見——細胞は再プログラムできる。それが人間の寿命に何を意味するか。', category: 'science', categoryLabel: 'Science & Mind', categoryLabelJa: '科学・思想', slug: 'yamanaka-factors-ageing', image: '/images/articles/yamanaka-factors-ageing.jpeg' },
  { num: '25', title: 'The Simulation Hypothesis: How Seriously Should We Take It?', blurb: "Nick Bostrom's argument is logically airtight. That doesn't mean the conclusion isn't disturbing.", titleJa: 'シミュレーション仮説：どこまで真剣に考えるべきか', blurbJa: 'ニック・ボストロムの論証は論理的に隙がない。だからといって結論が不穏でないわけではない。', category: 'science', categoryLabel: 'Science & Mind', categoryLabelJa: '科学・思想', slug: 'simulation-hypothesis', image: '/images/articles/simulation-hypothesis.jpeg' },

  // JAPAN & CULTURE
  { num: '26', title: 'The Harmony Paradox: How Cultures That Suppress Small Conflicts Produce Catastrophic Ones', blurb: 'A culture of harmony sounds safer. The historical record suggests the opposite.', titleJa: '調和のパラドックス：小さな衝突を抑圧する文化が大きな破局を生む理由', blurbJa: '調和の文化は安全に聞こえる。しかし歴史の記録はその逆を示唆している。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'harmony-paradox', image: '/images/articles/harmony-paradox.jpeg' },
  { num: '27', title: 'The Emergency That Never Ended: How Temporary Crises Become Permanent Cultures', blurb: "Japan's Meiji leaders said the emergency measures were temporary. They weren't. The pattern is everywhere.", titleJa: '終わらない緊急事態：一時的な危機が永続的な文化になる方法', blurbJa: '明治のリーダーは緊急措置は一時的だと言った。そうではなかった。このパターンはどこにでもある。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'emergency-that-never-ended', image: '/images/articles/emergency-that-never-ended.jpeg' },
  { num: '28', title: "Reading the Air: Japan's Invisible Legal System", blurb: "Japan's real rules aren't written down. They're in the air — and the enforcement is social, not institutional.", titleJa: '空気を読む：日本の見えない法体系', blurbJa: '日本の本当のルールは書かれていない。それは空気の中にある——そして執行は制度的ではなく社会的だ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'reading-the-air', image: '/images/articles/reading-the-air.jpeg' },
  { num: '30', title: 'Survival Mode vs Thriving Mode: The Two Moral Operating Systems', blurb: 'Most ethical disagreements are really about time horizons. Two modes of morality, both internally coherent, producing very different behaviour.', titleJa: 'サバイバルモードと繁栄モード：二つの道徳的オペレーティングシステム', blurbJa: 'ほとんどの倫理的対立は実際には時間軸の問題だ。どちらも内部的に一貫した二つの道徳モードが、非常に異なる行動を生む。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'survival-mode-vs-thriving-mode', image: '/images/articles/survival-mode-vs-thriving-mode.jpeg' },
  { num: '31', title: 'False Coherence: How Individuals and Societies Learn to Lie to Themselves', blurb: 'The story we tell to preserve our self-image. How it starts as a coping mechanism and ends as a liability.', titleJa: '偽りの一貫性：個人と社会が自分自身に嘘をつく方法', blurbJa: '自己イメージを守るために語る物語。コーピングメカニズムとして始まり、負債として終わる。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'false-coherence', image: '/images/articles/false-coherence.jpeg' },
  { num: '32', title: 'Why Free People Make Others Uncomfortable', blurb: "It's not what you've done. It's the question your existence silently asks: was the cost they paid actually necessary?", titleJa: '自由な人がなぜ他者を不快にするのか', blurbJa: 'あなたが何をしたかではない。あなたの存在が静かに問いかけることだ：彼らが払った代償は本当に必要だったのか？', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'why-free-people-make-others-uncomfortable', image: '/images/articles/why-free-people-make-others-uncomfortable.jpeg' },
  { num: '33', title: 'How Rules Stop Being Rules and Start Being Morality', blurb: 'Rules start as practical solutions. Then the context changes, but the rule stays — and somewhere it stops being a rule and becomes a moral truth.', titleJa: 'ルールがルールでなくなり道徳になる方法', blurbJa: 'ルールは実用的な解決策として始まる。やがて文脈が変わるがルールは残る——そしてどこかでルールでなく道徳的真実になる。', category: 'theory', categoryLabel: 'Original Theory', categoryLabelJa: '独自理論', slug: 'how-rules-become-morality', image: '/images/articles/how-rules-become-morality.jpeg' },

  // JAPAN'S SOCIAL MAP SERIES
  { num: '34', title: "Japan's Two Standards of Truth: Tatemae and Honne", blurb: 'Japan has an official position and a practical reality. Both are real. Neither is exactly a lie. Navigating the gap is a basic social skill — and the entry point to understanding how Japan actually works.', titleJa: '日本の二つの真実の基準：建前と本音', blurbJa: '日本には公式の立場と実際の現実がある。両方とも本物だ。どちらも厳密には嘘ではない。その隙間を渡ることが基本的な社会的スキルだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'tatemae-and-honne', image: '/images/articles/tatemae-and-honne.jpeg' },
  { num: '34b', title: "Japan's Social Map: Uchi and Soto", blurb: "Every culture distinguishes insiders from outsiders. Japan's version is unusually conscious, unusually graduated, and unusually consequential — shaping language, behaviour, and moral obligation at every level of social life.", titleJa: '日本の社会地図：内と外', blurbJa: 'どの文化も内側と外側を区別する。日本版は異例なほど意識的で、異例なほど段階的で、異例なほど重大——言語、行動、道徳的義務をあらゆる社会生活レベルで形成する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'uchi-and-soto', image: '/images/articles/uchi-and-soto.png' },
  { num: '34c', title: "Japan's Social Map: The Rings", blurb: "In Western ethics, every person has equal moral standing. In Japan's traditional architecture, morality is concentric — and where someone sits in your rings determines not just how much you care, but what kind of treatment is even appropriate.", titleJa: '日本の社会地図：環', blurbJa: '西洋倫理では、すべての人が平等な道徳的地位を持つ。日本の伝統的な構造では、道徳は同心円状——誰があなたの環のどこに座るかが、どれほど気にかけるかだけでなく、どんな扱いが適切かさえも決定する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-rings', image: '/images/articles/the-rings.jpeg' },
  { num: '34d', title: "Japan's Social Map: The Ranking", blurb: "Uchi and soto tell you where someone sits relative to you. But within soto, Japan operates a second axis — status — that determines whether an outsider receives deference, indifference, or something darker.", titleJa: '日本の社会地図：ランキング', blurbJa: '内と外はあなたとの相対的な位置を示す。しかし外の中で、日本は第二の軸——地位——を運用する。それが部外者が敬意、無関心、あるいはより暗いものを受けるかを決定する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'the-ranking', image: '/images/articles/the-ranking.png' },

  // JAPAN'S TWO STANDARDS OF TRUTH SERIES
  { num: '34e', title: "Japan's Two Standards of Truth: The Craftsman and the Diplomat", blurb: 'Japan has a rigorous relationship with physical truth and a managed relationship with social truth. Understanding the difference changes everything.', titleJa: '日本の二つの真実の基準：職人と外交官', blurbJa: '日本は物理的真実に対して厳格で、社会的真実に対して管理された関係を持つ。その違いを理解することがすべてを変える。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-1-dual-epistemology', image: '/images/articles/anti-kaizen-1-dual-epistemology.png' },
  { num: '34f', title: "Japan's Two Standards of Truth: How the Feedback Loop Was Built — And Who Broke It", blurb: "Japan's managed relationship with social truth is not an ancient cultural essence. Edo Japan had functioning correction mechanisms. The Meiji period deliberately dismantled them.", titleJa: '日本の二つの真実の基準：フィードバックループはどのように構築され、誰が壊したのか', blurbJa: '日本の社会的真実との管理された関係は古来の文化的本質ではない。江戸日本には機能する修正メカニズムがあった。明治期がそれを意図的に解体した。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-2-edo-and-meiji', image: '/images/articles/anti-kaizen-2-edo-and-meiji.png' },
  { num: '34g', title: "Japan's Two Standards of Truth: The Falsification Apparatus", blurb: "The military period didn't just commit atrocities and conceal them. It built administrative systems to make honest accounting structurally impossible — in real time.", titleJa: '日本の二つの真実の基準：偽造装置', blurbJa: '軍事期は残虐行為を犯して隠蔽しただけではない。リアルタイムで誠実な説明を構造的に不可能にする行政システムを構築した。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-3-falsification-apparatus', image: '/images/articles/anti-kaizen-3-falsification-apparatus.jpeg' },
  { num: '34h', title: "Japan's Two Standards of Truth: Falsified Inspection Records", blurb: "Fukushima proved what happens when Japan's social-domain truth standard invades physical reality. The same standard has been applied to history for eighty years.", titleJa: '日本の二つの真実の基準：偽造された検査記録', blurbJa: '福島は日本の社会領域の真実基準が物理的現実に侵入するとどうなるかを証明した。同じ基準が八十年間歴史に適用されてきた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-4-inspection-records', image: '/images/articles/anti-kaizen-4-inspection-records.png' },
  { num: '34i', title: "Japan's Two Standards of Truth: The Ghost in the System", blurb: "The nationalist says nations are not machines. He's right — but wrong about what follows. Japan has performed radical social kaizen before.", titleJa: '日本の二つの真実の基準：システムの中の亡霊', blurbJa: '国家主義者は国家は機械ではないと言う。彼は正しい——しかしその後に続くことについては間違っている。日本は以前にも根本的な社会改善を行った。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'anti-kaizen-5-ghost-in-the-system', image: '/images/articles/anti-kaizen-5-ghost-in-the-system.png' },

  // JAPAN'S RELATIONSHIP WITH NEGATIVITY SERIES
  { num: '35', title: "Japan's Relationship with Negativity: Kotodama", blurb: 'In Japan, words are not just descriptions of reality. They participate in creating it. This ancient belief shapes everyday language — and runs directly against the kind of honest negative expression that reckoning requires.', titleJa: '日本とネガティビティの関係：言霊', blurbJa: '日本では、言葉は単なる現実の描写ではない。言葉は現実の創造に参加する。この古来の信念が日常言語を形成し、和解が必要とする誠実な否定的表現と対立する。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-1-kotodama', image: '/images/articles/negativity-1-kotodama.jpeg' },
  { num: '35b', title: "Japan's Relationship with Negativity: Gambaru and Shikata ga Nai", blurb: "Push through. Then accept and move on. Japan's two-part response to hardship is genuinely admirable — and leaves no room for the middle space where reckoning lives.", titleJa: '日本とネガティビティの関係：頑張ると仕方がない', blurbJa: '乗り越えよ。次に受け入れて前に進む。困難への日本の二段階の反応は真に称賛すべきだ——そして和解が生きる中間の空間に余地を残さない。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-2-gambaru', image: '/images/articles/negativity-2-gambaru.jpeg' },
  { num: '35c', title: "Japan's Relationship with Negativity: The Smooth Surface", blurb: "In Japan, expressing negative inner states isn't just personally uncomfortable — it imposes an unwanted burden on everyone present. The social surface must be kept smooth.", titleJa: '日本とネガティビティの関係：滑らかな表面', blurbJa: '日本では、否定的な内的状態を表現することは単に個人的に不快なだけでなく、場にいる全員に望まれない負担を課す。社会的表面は滑らかに保たれなければならない。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-3-smooth-surface', image: '/images/articles/negativity-3-smooth-surface.png' },
  { num: '35d', title: "Japan's Relationship with Negativity: The Cost", blurb: "The cultural architecture that keeps Japan's social surface smooth carries a price — stigma, somatisation, and silence for individuals; a collective inability to sit with difficult reality for the nation.", titleJa: '日本とネガティビティの関係：コスト', blurbJa: '日本の社会的表面を滑らかに保つ文化的アーキテクチャには代価がある——個人にはスティグマ、身体化、沈黙を。国家には困難な現実に座り込む集団的な無能力を。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'negativity-4-the-cost', image: '/images/articles/negativity-4-the-cost.jpeg' },

  // WHAT HUMOUR ACTUALLY IS SERIES
  { num: '36', title: 'What Humour Actually Is: The Structure of the Joke', blurb: 'Humor exists wherever anxiety exists. The laugh lives in the gap between violation and safety — which makes comedy one of the most honest windows into any culture.', titleJa: 'ユーモアとは実際何か：ジョークの構造', blurbJa: 'ユーモアは不安があるところにしか存在しない。笑いは違反と安全の間の隙間に宿る——つまりコメディはどんな文化への最も誠実な窓の一つだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'what-humor-actually-is', image: '/images/articles/what-humor-actually-is.png' },
  { num: '36b', title: 'What Humour Actually Is: Japanese Comedy and Restored Order', blurb: 'Manzai has a boke who disrupts and a tsukkomi who corrects. The laugh is in the restoration. This tells you exactly what Japan is most afraid of.', titleJa: 'ユーモアとは実際何か：日本のコメディと秩序の回復', blurbJa: '漫才にはボケとツッコミがいる。笑いは回復にある。これは日本が最も恐れているものを正確に教えてくれる。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'japan-comedy-restored-order', image: '/images/articles/japan-comedy-restored-order.png' },
  { num: '36c', title: "What Humour Actually Is: The West's Many Anxieties", blurb: 'American, British, Australian, Irish — each comic culture is a precise map of what its people feared most and found a way, through laughter, to survive.', titleJa: 'ユーモアとは実際何か：西洋の多くの不安', blurbJa: 'アメリカ、イギリス、オーストラリア、アイルランド——それぞれのコメディ文化は、その人々が最も恐れ、笑いを通じて生き延びた方法の正確な地図だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'the-wests-many-anxieties', image: '/images/articles/the-wests-many-anxieties.png' },
  { num: '36d', title: 'What Humour Actually Is: Banter', blurb: "Banter is flyting's informal descendant — ritualized insult as a language of closeness. The line between banter and bullying is not the words used but whether both parties feel safe enough to return fire.", titleJa: 'ユーモアとは実際何か：バンター', blurbJa: 'バンターはフライティングの非公式な子孫——親密さの言語としての儀式化された侮辱だ。バンターといじめの境界線は使われた言葉ではなく、両者が反撃できるほど安全だと感じているかどうかだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'banter', image: '/images/articles/banter.png' },

  // THE AUSTRALIAN SOCIAL SCRIPT SERIES
  { num: '37', title: 'The Australian Social Script: The Friendliness Mandate', blurb: "In Australia, warmth isn't optional. It's a performance requirement. And the people who pay the highest price are those whose natural register doesn't match the script.", titleJa: 'オーストラリアの社会スクリプト：友好性の義務', blurbJa: 'オーストラリアでは、温かさは任意ではない。それはパフォーマンスの要件だ。最も高い代価を払うのは、自然なレジスターがスクリプトに合わない人々だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'friendliness-mandate', image: '/images/articles/friendliness-mandate.jpeg' },
  { num: '37b', title: 'The Australian Social Script: Why Australia Learned to Test Strangers', blurb: 'The frontier. The convicts. The horizontal trust built when vertical trust had failed. Australian banter was never just friendliness — it was a diagnostic.', titleJa: 'オーストラリアの社会スクリプト：なぜオーストラリアは見知らぬ人を試すことを学んだのか', blurbJa: 'フロンティア、囚人、垂直的信頼が失われたときに構築された水平的信頼。オーストラリアのバンターは単なる友好性ではなかった——それは診断だった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'why-australia-tests-strangers', image: '/images/articles/why-australia-tests-strangers.jpeg' },
  { num: '37c', title: 'The Australian Social Script: The Ghost of the Frontier', blurb: "The frontier is gone. The social technology it produced is not. Australia is still running a threat-detection system calibrated for conditions that haven't existed for over a century.", titleJa: 'オーストラリアの社会スクリプト：フロンティアの亡霊', blurbJa: 'フロンティアは消えた。それが生み出した社会的技術は消えていない。オーストラリアは一世紀以上前に消えた状況に合わせて調整された脅威検知システムをまだ動かしている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'ghost-of-the-frontier', image: '/images/articles/ghost-of-the-frontier.jpeg' },
  // SEKIGAHARA SERIES
  { num: '38', title: 'Sekigahara: The Man on the Hill', blurb: "In the autumn of 1600, one young man's hesitation changed the course of Japanese civilisation.", titleJa: '関ヶ原：丘の上の男', blurbJa: '1600年の秋、一人の若者の躊躇が日本文明の行方を変えた。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-1-the-man-on-the-hill', image: '/images/articles/sekigahara-1-the-man-on-the-hill.png' },
  { num: '38b', title: 'Sekigahara: The Japan That Never Was', blurb: "Hideaki's betrayal handed Ieyasu victory. But it was closer than history remembers — and the alternative Japan was not a fantasy.", titleJa: '関ヶ原：あり得た日本', blurbJa: '秀秋の裏切りが家康に勝利をもたらした。しかし歴史が記憶するより僅差だった——そして別の日本は幻想ではなかった。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-2-the-japan-that-never-was', image: '/images/articles/sekigahara-2-the-japan-that-never-was.png' },
  { num: '38c', title: 'Sekigahara: The Machinery of Harmony', blurb: 'The stillness of Edo Japan was not a reflection of the people. The people were a reflection of the stillness.', titleJa: '関ヶ原：調和の機械', blurbJa: '江戸日本の静けさは人々の反映ではなかった。人々が静けさの反映だったのだ。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-3-the-machinery-of-harmony', image: '/images/articles/sekigahara-3-the-machinery-of-harmony.png' },
  { num: '38d', title: 'Sekigahara: A Different People', blurb: 'Remove the Tokugawa crucible and you get a recognisably Japanese people — but differently so.', titleJa: '関ヶ原：異なる人々', blurbJa: '徳川の坩堝を取り除けば、確かに日本人とわかる人々が得られる——しかし異なる形で。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-4-a-different-people', image: '/images/articles/sekigahara-4-a-different-people.jpeg' },
  { num: '38e', title: "Sekigahara: Variables, Not Constants", blurb: "Japan's institutional struggles are not destiny. They are history. And history can be changed.", titleJa: '関ヶ原：定数ではなく変数', blurbJa: '日本の制度的苦闘は運命ではない。それは歴史だ。そして歴史は変えられる。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'sekigahara-5-variables-not-constants', image: '/images/articles/sekigahara-5-variables-not-constants.png' },
  // THE INVISIBLE MAN SERIES
  { num: '39', title: "The Invisible Man: The Present Reality", blurb: "Asian men receive disproportionately low interest from non-Asian women in Western countries. Most people have noticed. Few discuss it directly.", titleJa: '見えない男：現在の現実', blurbJa: 'アジア系男性は西洋諸国で非アジア系女性から不釣り合いに低い関心しか受けない。ほとんどの人が気づいている。直接議論する人は少ない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-1-the-present-reality', image: '/images/articles/invisible-man-1-the-present-reality.png' },
  { num: '39b', title: "The Invisible Man: What Makes a Man Attractive", blurb: "Most people never question what they find attractive. It feels instinctive — almost biological. But spend time looking across cultures and that certainty starts to loosen.", titleJa: '見えない男：男性の魅力とは何か', blurbJa: 'ほとんどの人は自分が魅力的だと思うものを疑問視しない。本能的に、ほぼ生物学的に感じられる。しかし文化を越えて眺め始めると、その確信が緩み始める。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-2-what-makes-a-man-attractive', image: '/images/articles/invisible-man-2-what-makes-a-man-attractive.jpeg' },
  { num: '39c', title: "The Invisible Man: When Sensitivity Was Strength", blurb: "In the early 19th century, the most admired men in the Western world were poets — celebrated for emotional depth, aesthetic sensitivity, and the ability to articulate inner experience.", titleJa: '見えない男：感受性が強さだった時代', blurbJa: '19世紀初頭、西洋世界で最も尊敬された男性は詩人たちだった——感情の深さ、美的感受性、内なる経験を表現する能力で称えられた。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-3-when-sensitivity-was-strength', image: '/images/articles/invisible-man-3-when-sensitivity-was-strength.jpeg' },
  { num: '39d', title: "The Invisible Man: The Making of the Hard Man", blurb: "The Romantic ideal did not fade gradually. It was dismantled — quickly, deliberately, and for reasons that had little to do with what men are naturally like.", titleJa: '見えない男：硬い男の形成', blurbJa: 'ロマン主義の理想は徐々に消えたのではない。解体された——迅速に、意図的に、そして男性の本来の姿とはほとんど関係のない理由で。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-4-the-making-of-the-hard-man', image: '/images/articles/invisible-man-4-the-making-of-the-hard-man.png' },
  { num: '39e', title: "The Invisible Man: The Gold Rush", blurb: "In 1851 gold was discovered in Victoria. Within months tens of thousands of men from around the world had descended on regional Australia — and the masculine template that emerged would shape the culture for generations.", titleJa: '見えない男：ゴールドラッシュ', blurbJa: '1851年、ビクトリアで金が発見された。数ヶ月のうちに世界中から何万人もの男性がオーストラリア地方に押し寄せ——生まれた男性像は何世代にもわたって文化を形成することになった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-5-the-gold-rush', image: '/images/articles/invisible-man-5-the-gold-rush.png' },
  { num: '39f', title: "The Invisible Man: Different Environments, Different Men", blurb: "The differences between Eastern and Western masculine ideals did not appear suddenly in history. They have roots that go back to the fundamental conditions in which these civilisations developed.", titleJa: '見えない男：異なる環境、異なる男性', blurbJa: '東西の男性的理想の違いは歴史の中で突然現れたのではない。それらは文明が発展した基本的な条件にまで遡る根を持っている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-6-different-environments-different-men', image: '/images/articles/invisible-man-6-different-environments-different-men.png' },
  { num: '39g', title: "The Invisible Man: Did Beauty Shape the Face", blurb: "A hypothesis worth asking: if masculine ideals vary by culture and those ideals shape what people find attractive, could centuries of different selection pressures have produced measurable differences in physical appearance?", titleJa: '見えない男：美が顔を形成したのか', blurbJa: '問う価値のある仮説：男性的理想が文化によって異なり、それらの理想が人々が魅力的だと思うものを形成するなら、何世紀もの異なる選択圧力が外見に測定可能な違いをもたらした可能性はあるか。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-7-did-beauty-shape-the-face', image: '/images/articles/invisible-man-7-did-beauty-shape-the-face.png' },
  { num: '39h', title: "The Invisible Man: The Man Without a Love Interest", blurb: "When Bruce Lee became an international star in the early 1970s, he was arguably the most physically compelling action hero on screen. He almost never kissed anyone on screen.", titleJa: '見えない男：恋愛対象のない男', blurbJa: 'ブルース・リーが1970年代初頭に国際的スターになったとき、彼はおそらくスクリーン上で最も肉体的に魅力的なアクションヒーローだった。彼はスクリーン上でほとんど誰ともキスしなかった。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-8-the-man-without-a-love-interest', image: '/images/articles/invisible-man-8-the-man-without-a-love-interest.png' },
  { num: '39i', title: "The Invisible Man: The State Decides", blurb: "In 2021 China's broadcasting authority banned overly feminine male celebrities from national media. The term used was niang pao — girly or effeminate. The message was direct: this aesthetic had no place in the national landscape.", titleJa: '見えない男：国家が決める', blurbJa: '2021年、中国の放送当局は過度に女性的な男性有名人を国家メディアから禁止した。使われた用語は娘炮——女らしいまたは軟弱。メッセージは直接的だった：このような美学に国家の景観に居場所はないと。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-9-the-state-decides', image: '/images/articles/invisible-man-9-the-state-decides.png' },
  { num: '39j', title: "The Invisible Man: K-pop and Its Limits", blurb: "For the first time in living memory a male aesthetic originating in East Asia built mass appeal in the West entirely on its own terms. BTS filled stadiums across America and Europe. But the limits of that breakthrough matter as much as the breakthrough itself.", titleJa: '見えない男：K-POPとその限界', blurbJa: '生きた記憶の中で初めて、東アジア発祥の男性的美学が完全に独自の条件で西洋で大衆的な支持を得た。BTSはアメリカとヨーロッパ中のスタジアムを満員にした。しかしその突破口の限界は突破口そのものと同様に重要だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-10-kpop-and-its-limits', image: '/images/articles/invisible-man-10-kpop-and-its-limits.png' },
  { num: '39k', title: "The Invisible Man: Why He Was Never in the Picture", blurb: "This series began with a measurable fact. It ends with an explanation — not a simple one, but the accumulated residue of several distinct historical forces, each reinforcing the last.", titleJa: '見えない男：なぜ彼は決して写真に写らなかったのか', blurbJa: 'このシリーズは測定可能な事実から始まった。単純ではない説明で終わる——いくつかの異なる歴史的力の蓄積された残留物、それぞれが次を強化している。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'invisible-man-11-why-he-was-never-in-the-picture', image: '/images/articles/invisible-man-11-why-he-was-never-in-the-picture.jpeg' },
  // TO BE JAPANESE SERIES
  { num: '40', title: 'To Be Japanese: The Weight of the Identification', blurb: 'When a Japanese person says "I am Japanese" it carries something closer to an ontological claim. This series asks why — and what it costs.', titleJa: '日本人であること：帰属のある重さ', blurbJa: '日本人が「私は日本人だ」と言うとき、それは存在論的な主張に近い何かを帯びている。このシリーズはその理由と、それが何を代償とするかを問う。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'to-be-japanese', image: '/images/articles/to-be-japanese.jpeg' },
  { num: '40b', title: 'To Be Japanese: Why the Fusion Runs So Deep', blurb: 'For national identity to become as total as it did in Japan, several things had to happen simultaneously — geography, religion, language, and deliberate policy all pushing in the same direction.', titleJa: '日本人であること：融合がこれほど深く根付いた理由', blurbJa: '日本のナショナルアイデンティティがこれほど全体的なものになるには、いくつかのことが同時に起きなければならなかった——地理、宗教、言語、そして意図的な政策がすべて同じ方向に向かって。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'why-the-fusion-runs-so-deep', image: '/images/articles/why-the-fusion-runs-so-deep.png' },
  { num: '40c', title: 'To Be Japanese: What Reckoning Actually Costs', blurb: 'Imagine a Japanese person who arrives at a genuine personal reckoning with the war. What does that moment actually cost them — not politically, but personally?', titleJa: '日本人であること：清算が実際に何を代償とするか', blurbJa: '戦争について真の個人的な清算に至った日本人を想像してほしい。その瞬間は彼らに何を——政治的にではなく、個人的に——代償として課すのか。', category: 'japan', categoryLabel: 'Japan & Culture', categoryLabelJa: '日本・文化', slug: 'what-reckoning-actually-costs', image: '/images/articles/what-reckoning-actually-costs.png' },

  // THE DELTA FORGE — CULTURE CREATES THE FUTURE
  { num: '41', title: 'Culture Creates the Future: Why Culture Determines Your Economy', blurb: 'Economists explain national wealth through resources, labour costs, and geography. But comparative advantage is psychological before it is material — and the soil determines what grows.', titleJa: '文化が未来を作る：なぜ文化は経済を決定するのか', blurbJa: '経済学者は資源、労働コスト、地理によって国家の富を説明する。しかし比較優位は物質的である前に心理的だ——そして土壌が何が育つかを決める。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-01-cultural-comparative-advantage', image: '/images/articles/culture-creates-the-future-01-cultural-comparative-advantage.jpeg' },
  { num: '41b', title: 'Culture Creates the Future: How Automation Sharpens the Divide', blurb: 'Automation does not affect sea and floodplain civilisations equally. What gets compressed first, what remains, and what sharpens — the cultural dimension most analysis misses.', titleJa: '文化が未来を作る：自動化が分断をどのように鋭化するか', blurbJa: '自動化は海洋文明と氾濫原文明に等しく影響しない。最初に圧縮されるもの、残るもの、鋭化されるもの——ほとんどの分析が見逃す文化的次元。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-02-automation-sharpens-the-divide', image: '/images/articles/culture-creates-the-future-02-automation-sharpens-the-divide.png' },
  { num: '41c', title: 'Culture Creates the Future: Two Nations, Two Strategies, Two Futures', blurb: 'Japan and Australia as embodiments of opposite responses to the same civilisational moment. One chose the lower floor and the lower ceiling. The other is living with the consequences of having chosen neither.', titleJa: '文化が未来を作る：二つの国家、二つの戦略、二つの未来', blurbJa: '同じ文明的瞬間への反対の反応を体現する日本とオーストラリア。一方は低い床と低い天井を選んだ。もう一方はどちらも選ばなかった結果と共に生きている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-03-two-nations-two-strategies', image: '/images/articles/culture-creates-the-future-03-two-nations-two-strategies.png' },
  { num: '41d', title: "Culture Creates the Future: Australia's Demographic Bet", blurb: "Australia is running a civilisational experiment whose outcome is genuinely uncertain. Floodplain cultural instincts operating inside sea-culture institutions — high variance, extraordinary upside, real downside.", titleJa: '文化が未来を作る：オーストラリアの人口統計的賭け', blurbJa: 'オーストラリアは結果が真に不確実な文明的実験を行っている。海洋文化の制度の中で動く氾濫原の文化的本能——高分散、非凡なアップサイド、本物のダウンサイド。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-04-australias-demographic-bet', image: '/images/articles/culture-creates-the-future-04-australias-demographic-bet.jpeg' },
  { num: '41e', title: 'Culture Creates the Future: The Creator Economy and the Wealth of Worlds', blurb: 'When production cost collapses toward zero, what remains scarce is a distinctive worldview. Japan holds centuries of accumulated aesthetic capital. Australia holds positional hybridity. Neither can be replicated by the other.', titleJa: '文化が未来を作る：クリエイターエコノミーと世界の富', blurbJa: '制作コストがゼロに向かって崩壊するとき、稀少なままのものは独特の世界観だ。日本は何世紀もの蓄積された美的資本を保有する。オーストラリアは位置的なハイブリッド性を。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-05-creator-economy-wealth-of-worlds', image: '/images/articles/culture-creates-the-future-05-creator-economy-wealth-of-worlds.png' },
  { num: '41f', title: 'Culture Creates the Future: Where Creators Go For Inspiration', blurb: 'Japan offers something Singapore structurally cannot — cultural depth accumulated over centuries. Creators do not need to live in Japan permanently to be shaped by it. They need periodic, genuine immersion.', titleJa: '文化が未来を作る：クリエイターはどこにインスピレーションを求めるか', blurbJa: '日本はシンガポールが構造的に提供できないものを提供する——何世紀にもわたって蓄積された文化的深さ。クリエイターはそれによって形成されるために日本に永続的に住む必要はない。定期的な、本物の没入が必要だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-06-where-creators-go-for-inspiration', image: '/images/articles/culture-creates-the-future-06-where-creators-go-for-inspiration.jpeg' },
  { num: '41g', title: 'Culture Creates the Future: Where Creators Actually Live', blurb: 'Inspiration and habitation are different needs. A layered ecosystem — Japan for deep inspiration, Singapore for lean operations, Australia for long-term habitation. No single nation captures everything.', titleJa: '文化が未来を作る：クリエイターが実際に住む場所', blurbJa: 'インスピレーションと居住は異なるニーズだ。層状のエコシステム——深いインスピレーションのための日本、無駄のない運営のためのシンガポール、長期的な居住のためのオーストラリア。どの単一の国家もすべてを獲得しない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-07-where-creators-live', image: '/images/articles/culture-creates-the-future-07-where-creators-live.jpeg' },
  { num: '41h', title: 'Culture Creates the Future: The Individual Universe', blurb: 'When AI makes cinematic production accessible to individuals, the universe model becomes available at the individual level. The hybrid creator — fluent across civilisations, grounded in depth — is the profile this entire moment is selecting for.', titleJa: '文化が未来を作る：個人の宇宙', blurbJa: 'AIが映画的制作を個人に利用可能にするとき、宇宙モデルは個人レベルで利用可能になる。文明にわたって流暢で、深みに根ざしたハイブリッドクリエイター——それがこの瞬間全体が選択しているプロフィールだ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'culture-creates-the-future-08-the-individual-universe', image: '/images/articles/culture-creates-the-future-08-the-individual-universe.png' },

  // THE WHOLE AND THE PART SERIES
  { num: '42', title: 'The Whole and the Part: The Cosmological Fork', blurb: 'The date, the address, the name — three mundane conventions, all pointing in the same direction. A difference in assumption so deep it shapes how entire cultures organise time, space, and identity simultaneously.', titleJa: '全体と部分：宇宙論的な分岐点', blurbJa: '日付、住所、名前——三つの平凡な慣習、すべてが同じ方向を指している。文化全体が時間、空間、アイデンティティをどのように組織するかを形成するほど深い前提の違い。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-1-the-cosmological-fork', image: '/images/articles/article-1-the-cosmological-fork.jpeg' },
  { num: '42b', title: 'The Whole and the Part: The Language of Survival', blurb: 'Why indirect communication is not a personality flaw but a cosmological consequence. One culture uncomfortable with disruption, the other with silence — both protecting belonging from opposite directions.', titleJa: '全体と部分：生存の言語', blurbJa: 'なぜ間接的なコミュニケーションは性格の欠点ではなく宇宙論的な帰結なのか。一方の文化は混乱に不快感を覚え、もう一方は沈黙に——両方とも反対方向から帰属を守っている。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-2-the-language-of-survival', image: '/images/articles/article-2-the-language-of-survival.png' },
  { num: '42c', title: 'The Whole and the Part: Connection as Assumption', blurb: 'Why one culture thinks relationships need to be built and the other thinks they need to be protected. One cannot name its problems. The other cannot rest inside its relationships.', titleJa: '全体と部分：前提としてのつながり', blurbJa: 'なぜ一方の文化は関係を構築する必要があると考え、もう一方は守る必要があると考えるのか。一方は問題を名付けられない。もう一方は関係の中で休めない。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-3-connection-as-assumption', image: '/images/articles/article-3-connection-as-assumption.png' },
  { num: '42d', title: 'The Whole and the Part: Symmetric Insecurities', blurb: 'Neither culture is more evolved — they are just afraid of different things. Both fears are rational responses to their respective cosmologies. Both have institutionalised their anxiety into a very sophisticated survival mode.', titleJa: '全体と部分：対称的な不安', blurbJa: 'どちらの文化もより進化しているわけではない——単に異なるものを恐れているだけだ。両方の恐れはそれぞれの宇宙論への合理的な反応だ。両方が不安を洗練されたサバイバルモードへと制度化した。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-4-symmetric-insecurities', image: '/images/articles/article-4-symmetric-insecurities.png' },
  { num: '42e', title: 'The Whole and the Part: The Structural Solution', blurb: 'What Scandinavia suggests about the relationship between security and communication. Directness, comfort with silence, the ability to surface conflict: not virtues you choose, but capacities that security makes available.', titleJa: '全体と部分：構造的解決策', blurbJa: 'スカンジナビアが安心とコミュニケーションの関係について示唆すること。直接性、沈黙への安心、対立を浮上させる能力——選ぶ美徳ではなく、安心が利用可能にする能力だ。', category: 'culture', categoryLabel: 'Culture & Society', categoryLabelJa: '文化・社会', slug: 'article-5-the-structural-solution', image: '/images/articles/article-5-the-structural-solution.png' },
]

export const categories = [
  { key: 'all', label: 'All', labelJa: 'すべて' },
  { key: 'culture', label: 'Culture & Society', labelJa: '文化・社会' },
  { key: 'spirituality', label: 'Spirituality', labelJa: '精神・宗教' },
  { key: 'theory', label: 'Original Theory', labelJa: '独自理論' },
  { key: 'history', label: 'History & Myth', labelJa: '歴史・神話' },
  { key: 'science', label: 'Science & Mind', labelJa: '科学・思想' },
  { key: 'japan', label: 'Japan & Culture', labelJa: '日本・文化' },
]

export const categoryGroups = [
  { key: 'culture', label: 'Culture & Society', labelJa: '文化・社会' },
  { key: 'spirituality', label: 'Spirituality & Religion', labelJa: '精神・宗教' },
  { key: 'theory', label: 'Original Theories', labelJa: '独自理論' },
  { key: 'history', label: 'History & Mythology', labelJa: '歴史・神話' },
  { key: 'science', label: 'Science & Mind', labelJa: '科学・思想' },
  { key: 'japan', label: 'Japan & Culture', labelJa: '日本・文化' },
]